package net.ahm.activemeasure.cdm.year2016.ACO.AM127_Ambulatory_Care_Sensitive_Conditions_Admissions_For_Heart_Failure

import net.ahm.careengine.domain.member.MemberInfo
import net.ahm.careengine.domain.event.claim.ClaimHeader
import net.ahm.careengine.domain.measures.active.ActiveMeasure
import net.ahm.careengine.domain.member.ActiveMeasuresMemberInfo
import net.ahm.careengine.util.GlobalFunctions
import net.ahm.careengine.service.activemeasure.ActiveMeasureCommandOutputIF
import net.ahm.careengine.domain.member.Gender
import net.ahm.careengine.domain.measures.active.ActiveMeasure
import net.ahm.careengine.domain.member.ActiveMeasuresMemberInfo
import net.ahm.careengine.domain.measures.active.ActiveMeasureRuleContext
import net.ahm.careengine.domain.measures.active.ActiveMeasure
import net.ahm.careengine.domain.event.lab.LabEvent
import net.ahm.careengine.domain.event.proc.ProcedureEvent
import net.ahm.careengine.domain.event.diag.DiagnosticEvent
import net.ahm.careengine.domain.measures.active.impl.MemberActiveMeasure
import net.ahm.careengine.domain.event.drug.DrugEvent
import net.ahm.careengine.util.OverlappedEvents
import net.ahm.careengine.util.GlobalFunctions
import net.ahm.careengine.service.activemeasure.ActiveMeasureCommandOutputIF
import java.util.Collection
import java.util.Date
import net.ahm.careengine.domain.feedback.Feedback
import net.ahm.careengine.domain.measures.active.ActiveMeasureBuilder
import net.ahm.careengine.domain.event.claim.ClaimHeader
import net.ahm.careengine.domain.event.clinical.HieEncounter
import net.ahm.careengine.event.adt.model.DischargeDispositionStatus
import net.ahm.careengine.domain.event.pdd.PatientDerivedEvent
import net.ahm.careengine.domain.event.lab.LabResultEvent
import net.ahm.careengine.bom.clinical.HieMood
import net.ahm.careengine.ruleengine.DroolEditor
import net.ahm.careengine.ruleengine.DateTimeUnit
import net.ahm.careengine.domain.event.Event
import net.ahm.careengine.domain.event.adt.BaseAdmissionDischardTransferEvent
import org.joda.time.LocalDate
import net.ahm.careengine.domain.temporal.ContiguousDays
import net.ahm.careengine.domain.measures.active.FactLevelMeasureNumerator
import net.ahm.careengine.domain.measures.active.FactLevelMeasureDenominator
import net.ahm.careengine.domain.measures.active.FactLevelMeasureBuilder

global java.util.Date measurementEndDate
global net.ahm.careengine.domain.measures.active.ActiveMeasureBuilder activeMeasureBuilder
global java.util.Date months12BeforeMeasurementEndDate
global java.util.Date years10BeforeMeasurementEndDate
global java.util.Date years5BeforeMeasurementEndDate
global java.util.Date months24BeforeMeasurementEndDate
global java.util.Date months3BeforeMeasurementEndDate
global java.util.Date months1BeforeMeasurementEndDate
global java.util.Date measurementStartDate
global net.ahm.careengine.domain.measures.active.FactLevelMeasureBuilder factLevelMeasureBuilder



















rule "AM127_DENOM_HEART_FAILURE"
	dialect "mvel"
	when
		 ActiveMeasuresMemberInfo( ageAtMeasurementEndDate >= 18 , gender != null )
		 $claimHdr : ClaimHeader( endDate <= measurementEndDate , endDate >= months12BeforeMeasurementEndDate , claimType == ClaimType.INPAT  || == ClaimType.OUTPAT  || == ClaimType.INPAT_FULLENC , allDiagnosticEventElements contains 7932 )
	then
		FactLevelMeasureDenominator flmDenominator= factLevelMeasureBuilder.newFactLevelMeasureDenominatorWithPrimaryFact(127, $claimHdr); insert(flmDenominator)
end


rule "AM127_NUM"
	dialect "mvel"
	when
		 $flm : FactLevelMeasureDenominator( measureId == 127 , $firstAdmission : primaryOriginationFact != null )
		 $readmission : ClaimHeader( this != $firstAdmission , endDate <= measurementEndDate , endDate >= months12BeforeMeasurementEndDate , principalDiagnosisElements contains 7932 , claimType == ClaimType.INPAT  || == ClaimType.INPAT_FULLENC )
	then
		FactLevelMeasureNumerator flmNumerator = $flm.createFactLevelMeasureNumeratorWithPrimaryFact($readmission); insert(flmNumerator);
end


rule "AM127_NUM_EXCL_ADMISSIONS_SAME_DAY_DIFF_FACILITY"
	dialect "mvel"
	when
		 $flmNum : FactLevelMeasureNumerator( measureId == 127 , $primaryOrigFact : primaryFact != null , factLevelDenominator != null , $primaryOrigFactFromDenom : factLevelDenominator.primaryOriginationFact != null )
		 $indexEvent : ClaimHeader( $indexAdmissionAdmittingDate : startDate != null , $indexAdmissionFacility : servicingOrgId != null ) from $primaryOrigFactFromDenom
		$1dayAfterIndexAdmission : java.util.Date() from GlobalFunctions.getLaterDate($indexAdmissionAdmittingDate, 1, DateTimeUnit.DAY)
		 $readmissionEvent : ClaimHeader( startDate < ( $1dayAfterIndexAdmission ) , startDate >= $indexAdmissionAdmittingDate , servicingOrgId != $indexAdmissionFacility ) from $primaryOrigFact
	then
		 $flmNum.setExcludedFromNumerator( true );
end


rule "AM127_NUM_EXCL_CARDIAC_PROC"
	dialect "mvel"
	when
		$flmNum : FactLevelMeasureNumerator( measureId == 127 , $primaryOrigFact : primaryFact != null )
		ClaimHeader( relatedProcedureEventElements contains 7933 ) from $primaryOrigFact
	then
		$flmNum.setExcludedFromNumerator( true );
end


