package net.ahm.activemeasure.medicalcase.year2015.aetnameasures.AdverseEvent_Rate_Acute_Inpatient_2015

import net.ahm.careengine.domain.member.MemberInfo
import net.ahm.careengine.domain.event.claim.ClaimHeader
import net.ahm.careengine.domain.measures.active.ActiveMeasure
import net.ahm.careengine.domain.member.ActiveMeasuresMemberInfo
import net.ahm.careengine.util.GlobalFunctions
import net.ahm.careengine.service.activemeasure.ActiveMeasureCommandOutputIF
import net.ahm.careengine.domain.member.Gender
import net.ahm.careengine.domain.measures.active.ActiveMeasureRuleContext
import net.ahm.careengine.domain.event.lab.LabEvent
import net.ahm.careengine.domain.event.proc.ProcedureEvent
import net.ahm.careengine.domain.event.diag.DiagnosticEvent
import net.ahm.careengine.domain.measures.active.impl.MemberActiveMeasure
import net.ahm.careengine.domain.event.drug.DrugEvent
import net.ahm.careengine.util.OverlappedEvents
import java.util.Collection
import java.util.Date
import net.ahm.careengine.domain.feedback.Feedback
import net.ahm.careengine.domain.measures.active.ActiveMeasureBuilder
import net.ahm.careengine.domain.event.clinical.HieEncounter
import net.ahm.careengine.event.adt.model.DischargeDispositionStatus
import net.ahm.careengine.domain.event.pdd.PatientDerivedEvent
import net.ahm.careengine.domain.event.lab.LabResultEvent
import net.ahm.careengine.bom.clinical.HieMood
import net.ahm.careengine.ruleengine.DroolEditor
import net.ahm.careengine.ruleengine.DateTimeUnit
import net.ahm.careengine.domain.event.Event
import net.ahm.careengine.domain.event.adt.BaseAdmissionDischardTransferEvent
import org.joda.time.LocalDate
import net.ahm.careengine.domain.temporal.ContiguousDays
import net.ahm.careengine.domain.measures.active.FactLevelMeasureNumerator
import net.ahm.careengine.domain.measures.active.FactLevelMeasureDenominator
import net.ahm.careengine.domain.measures.active.FactLevelMeasureBuilder
import net.ahm.careengine.domain.event.claim.ClaimLabResultInfo
import net.ahm.careengine.domain.event.claim.ClaimBaseInfo
import net.ahm.careengine.domain.event.claim.ClaimLabInfo
import net.ahm.careengine.domain.event.claim.ClaimDiagnosticInfo
import net.ahm.careengine.domain.event.claim.ClaimProcedureInfo
import net.ahm.careengine.domain.event.claim.ClaimDrugInfo
import net.ahm.careengine.domain.classifier.Classifier
import net.ahm.careengine.domain.classifier.ClassifierBuilder
import net.ahm.careengine.domain.medicalcase.MedicalCase
import net.ahm.careengine.domain.medicalcase.MedicalCaseProviderInfo
import net.ahm.careengine.domain.medicalcase.MedicalCaseClaim
import net.ahm.careengine.domain.medicalcase.MedicalCaseClaimDiagnosis
import net.ahm.careengine.domain.medicalcase.MedicalCaseAffiliation

global java.util.Date measurementEndDate
global net.ahm.careengine.domain.measures.active.ActiveMeasureBuilder activeMeasureBuilder
global java.util.Date months12BeforeMeasurementEndDate
global java.util.Date years10BeforeMeasurementEndDate
global java.util.Date years5BeforeMeasurementEndDate
global java.util.Date months24BeforeMeasurementEndDate
global java.util.Date months3BeforeMeasurementEndDate
global java.util.Date months1BeforeMeasurementEndDate
global java.util.Date measurementStartDate
global net.ahm.careengine.domain.measures.active.FactLevelMeasureBuilder factLevelMeasureBuilder
global net.ahm.careengine.domain.measures.active.ActiveMeasureClassifierBuilder classifierBuilder
global java.util.Date months11BeforeMeasurementEndDate








rule "DENOM_ADVERSE_EVENT_RATE"
	dialect "mvel"
	when
		$medicalCase : MedicalCase( medicalCaseEndDate >= months12BeforeMeasurementEndDate , facility != null , facility.EPDBSpecialtyCategoryCode == "WHOS"  || == "WCH" , placeOfServiceCategoryCode == "I" , adverseEventExpected != null  && != 0 , adverseEventEvaluationCode == "1"  || == "2"  || == "4" , medicalCaseEndDate <= measurementEndDate )
	then
		FactLevelMeasureDenominator flmDenominator= factLevelMeasureBuilder.newFactLevelMeasureDenominatorWithPrimaryFact(85,$medicalCase); insert(flmDenominator)
end


rule "NUM_ADVERSE_EVENT_RATE"
	dialect "mvel"
	when
		$flDenom : FactLevelMeasureDenominator( measureId == 85 , $primaryOrigin : primaryOriginationFact != null )
		$medicalCase : MedicalCase( this == $primaryOrigin , adverseEventEvaluationCode == "4"  || == "1" )
	then
		FactLevelMeasureNumerator flmNumerator = $flDenom.createFactLevelMeasureNumeratorWithPrimaryFact($medicalCase); insert(flmNumerator);
end


rule "DENOM_EXCL_DRG_CODE_ADVERSE_EVENT_RATE"
	dialect "mvel"
	when
		$flDenom : FactLevelMeasureDenominator( measureId == 85 , $primaryOriginEvent : primaryOriginationFact != null )
		$medicalCase : MedicalCase( this == $primaryOriginEvent , diagnosisRelatedGroupElements contains 9247  || contains 9243 )
	then
		$flDenom.setExcludedFromDenominator( true );
end
















