package net.ahm.activemeasure.qualitymeasures.year2015.HEDIS.HEDIS_Appropriate_Medications_For_People_With_Asthma_2015

import net.ahm.careengine.domain.member.MemberInfo
import net.ahm.careengine.domain.measures.active.impl.MemberActiveMeasure
import net.ahm.careengine.domain.measures.active.ActiveMeasure
import net.ahm.careengine.domain.event.proc.ProcedureEvent
import net.ahm.careengine.domain.event.diag.DiagnosticEvent
import net.ahm.careengine.domain.member.GenderSelection
import net.ahm.careengine.service.activemeasure.ActiveMeasureCommandOutputIF
import net.ahm.careengine.domain.member.Gender
import net.ahm.careengine.ruleengine.DroolEditor
import net.ahm.careengine.domain.event.drug.DrugEvent
import net.ahm.careengine.domain.measures.active.ActiveMeasureRuleContext
import net.ahm.careengine.util.GlobalFunctions
import net.ahm.careengine.ruleengine.DateTimeUnit
import java.util.Collection
import java.util.Date
import net.ahm.careengine.domain.event.CodifiedEvent
import net.ahm.careengine.domain.event.lab.LabEvent
import net.ahm.careengine.domain.event.lab.LabResultEvent
import net.ahm.careengine.util.OverlappedEvents
import net.ahm.careengine.domain.classifier.Classifier
import net.ahm.careengine.domain.classifier.ClassifierBuilder
import net.ahm.careengine.domain.feedback.Feedback
import net.ahm.careengine.domain.event.claim.ClaimHeader
import net.ahm.careengine.domain.event.clinical.HieEncounter
import net.ahm.careengine.event.adt.model.DischargeDispositionStatus
import net.ahm.careengine.domain.member.ActiveMeasuresMemberInfo
import net.ahm.careengine.domain.event.pdd.PatientDerivedEvent
import net.ahm.careengine.domain.event.Event
import net.ahm.careengine.util.CEDateUtil
import net.ahm.careengine.domain.temporal.TemporalUtil
import net.ahm.careengine.util.Month
import net.ahm.careengine.domain.event.adt.BaseAdmissionDischardTransferEvent
import net.ahm.careengine.domain.event.drug.DrugDispensingEvent

global java.util.Date measurementEndDate
global net.ahm.careengine.domain.measures.active.ActiveMeasureBuilder activeMeasureBuilder
global java.util.Date months12BeforeMeasurementEndDate
global java.util.Date months24BeforeMeasurementEndDate
global java.util.Date months27BeforeMeasurementEndDate
global java.util.Date years10BeforeMeasurementEndDate
global java.util.Date years5BeforeMeasurementEndDate
global java.util.Date months6BeforeMeasurementEndDate
global java.util.Date years3BeforeMeasurementEndDate
global net.ahm.careengine.domain.measures.active.ActiveMeasureClassifierBuilder classifierBuilder





rule "DENOM_ASTMA_MEDS"
	dialect "mvel"
	when
		 ActiveMeasuresMemberInfo( ageAtMeasurementEndDate >= 5 , ageAtMeasurementEndDate <= 64 )
		 java.util.Collection( empty == false ) from collect ( Classifier( id in ( 49, 38, 36, 51, 37 ) )) 
		 java.util.Collection( empty == false ) from collect ( Classifier( id in ( 50, 41, 39, 52, 40 ) )) 
	then
		ActiveMeasure mam = activeMeasureBuilder.newActiveMeasure(44); insert(mam)
end


rule "DENOM_EXCL_ASTHMA"
	dialect "mvel"
	when
		$am : ActiveMeasure(measureId == 44)
		 DiagnosticEvent( elements contains 6011 , endDate <= measurementEndDate )
	then
		$am.setExcludedFromDenominator(true)
end


rule "NUM_ASTHMA_MEDS_DRUG"
	dialect "mvel"
	when
		$am : ActiveMeasure(measureId == 44)
		 DrugEvent( elements contains 8971 , endDate <= measurementEndDate , endDate >= months12BeforeMeasurementEndDate )
	then
		$am.setInNumerator(true)
end


rule "NUM_ASTHMA_MEDS_PDD"
	dialect "mvel"
	when
		$am : ActiveMeasure(measureId == 44)
		 PatientDerivedEvent( elements contains 8525 , endDate <= measurementEndDate , endDate >= months12BeforeMeasurementEndDate )
	then
		$am.setInNumerator(true)
end


rule "DENOM_EXCL_PDD_PERSISTENT_ASTHMA_EXCL_DX"
	dialect "mvel"
	when
		$am : ActiveMeasure(measureId == 44)
		 PatientDerivedEvent( elements contains 8527 , endDate <= measurementEndDate , endDate >= months12BeforeMeasurementEndDate )
	then
		$am.setExcludedFromDenominator(true)
end


rule "DENOM_EXCL_PDD_NO_PERSISTENT_ASTHMA"
	dialect "mvel"
	when
		$am : ActiveMeasure(measureId == 44)
		 PatientDerivedEvent( elements contains 8526 , endDate <= measurementEndDate , endDate >= months12BeforeMeasurementEndDate )
	then
		$am.setExcludedFromDenominator(true)
end












