package net.ahm.activemeasure.qualitymeasures.year2015.ACO.ACO_Preventive_Care_BMI_Screening_And_Follow_Up_2015

import net.ahm.careengine.domain.measures.active.ActiveMeasure
import net.ahm.careengine.domain.member.ActiveMeasuresMemberInfo
import net.ahm.careengine.domain.member.GenderSelection
import net.ahm.careengine.domain.measures.active.ActiveMeasureRuleContext
import net.ahm.careengine.domain.event.lab.LabEvent
import net.ahm.careengine.domain.event.proc.ProcedureEvent
import net.ahm.careengine.domain.event.diag.DiagnosticEvent
import net.ahm.careengine.domain.measures.active.impl.MemberActiveMeasure
import net.ahm.careengine.domain.event.drug.DrugEvent
import net.ahm.careengine.domain.member.MemberInfo
import net.ahm.careengine.util.GlobalFunctions
import net.ahm.careengine.ruleengine.DateTimeUnit
import net.ahm.careengine.domain.member.Gender
import net.ahm.careengine.ruleengine.DroolEditor
import java.util.Date
import java.util.Collection
import net.ahm.careengine.domain.temporal.Temporal
import net.ahm.careengine.domain.temporal.ContiguousDays
import net.ahm.careengine.domain.measures.active.ActiveMeasureBuilder
import net.ahm.careengine.domain.findings.MeasureFindingObjectFactory
import net.ahm.careengine.bom.clinical.HieLabStatus
import net.ahm.careengine.bom.clinical.HieSectionType
import net.ahm.careengine.domain.measures.active.ActiveMeasure
import net.ahm.careengine.bom.Operator.GEResponse
import net.ahm.careengine.domain.temporal.SpanComparator
import net.ahm.careengine.bom.clinical.HieProblemPhase
import net.ahm.careengine.bom.clinical.HieSource
import net.ahm.careengine.domain.findings.DenomFinding
import net.ahm.careengine.domain.event.claim.ClaimDrugInfo
import net.ahm.careengine.domain.event.lab.LabResultEvent
import net.ahm.careengine.bom.Operator.EXResponse
import net.ahm.careengine.bom.clinical.HieProblemLevel
import net.ahm.careengine.common.CECollectionsUtil
import net.ahm.careengine.bom.Operator.NMBTResponse
import net.ahm.careengine.domain.temporal.TemporalUtil
import net.ahm.careengine.domain.provider.CareProvider
import net.ahm.careengine.domain.temporal.Span
import net.ahm.careengine.domain.findings.Finding
import net.ahm.careengine.bom.clinical.HieProblemStatus
import net.ahm.careengine.util.CEDateUtil
import net.ahm.careengine.bom.clinical.HieProblemType
import net.ahm.careengine.util.ThreadLocalSimpleDateFormat
import net.ahm.careengine.domain.event.EventType
import net.ahm.careengine.domain.findings.DenomExclusionFinding
import net.ahm.careengine.bom.response.IResponse
import net.ahm.careengine.domain.temporal.BaseTemporal
import net.ahm.careengine.domain.temporal.Day
import net.ahm.careengine.common.Constants
import net.ahm.careengine.domain.member.MemberProfile
import net.ahm.careengine.domain.event.EventCode
import net.ahm.careengine.domain.event.Event
import net.ahm.careengine.domain.findings.NumeratorCompletionFinding
import net.ahm.careengine.command.CommandConfigurationIF
import net.ahm.careengine.domain.findings.MeasureFinding
import net.ahm.careengine.domain.temporal.FilteredTemporals
import net.ahm.careengine.bom.Operator.NBTResponse
import net.ahm.careengine.domain.event.lab.LabOrgEvent
import net.ahm.careengine.bom.Operator
import net.ahm.careengine.domain.event.pdd.PatientDerivedEvent
import net.ahm.careengine.bom.Operator.BTResponse
import net.ahm.careengine.command.CommandContextIF
import net.ahm.careengine.bom.clinical.HieMood
import net.ahm.careengine.domain.event.allergy.AllergyEvent
import net.ahm.careengine.bom.member.event.pd.PatientDerivedEventType
import net.ahm.careengine.domain.event.drug.DrugGNICode
import net.ahm.careengine.bom.clinical.HieDrugStatus
import net.ahm.careengine.bom.Operator.EQResponse
import net.ahm.careengine.domain.event.drug.DrugClassCode
import net.ahm.careengine.command.CommandOutputIF
import net.ahm.careengine.domain.event.CodifiedEvent
import net.ahm.careengine.bom.Operator.GTResponse
import net.ahm.careengine.domain.event.drug.DrugGTICode
import net.ahm.careengine.domain.fact.Fact
import net.ahm.careengine.bom.Operator.LEResponse
import net.ahm.careengine.bom.Operator.LTResponse
import net.ahm.careengine.bom.clinical.HieData
import net.ahm.careengine.domain.findings.NumeratorComplianceFinding
import net.ahm.careengine.domain.event.claim.ClaimLabInfo
import net.ahm.careengine.bom.clinical.ProcedureStatus
import net.ahm.careengine.domain.event.EventSourceType
import net.ahm.careengine.bom.Operator.MBTResponse
import net.ahm.careengine.domain.feedback.Feedback.FeedbackReferenceType
import net.ahm.careengine.domain.feedback.Feedback
import net.ahm.careengine.util.OverlappedEvents
import java.util.Set
import net.ahm.careengine.domain.event.EventSourceType
import net.ahm.careengine.domain.event.Event
import net.ahm.careengine.domain.event.claim.ClaimHeader
import net.ahm.careengine.domain.event.clinical.HieEncounter
import net.ahm.careengine.event.adt.model.DischargeDispositionStatus
import net.ahm.careengine.util.GlobalFunctions

global java.util.Date measurementEndDate
global net.ahm.careengine.domain.measures.active.ActiveMeasureBuilder activeMeasureBuilder
global net.ahm.careengine.domain.classifier.ClassifierBuilder classifierBuilder
global java.util.Date months12BeforeMeasurementEndDate
global java.util.Date months24BeforeMeasurementEndDate
global java.util.Date months27BeforeMeasurementEndDate
global java.util.Date years10BeforeMeasurementEndDate
global java.util.Date years5BeforeMeasurementEndDate
global java.util.Date months6BeforeMeasurementEndDate



















rule "DENOM_ACO_16_QM_ENCOUNTER_ADULT_PROC"
	dialect "mvel"
	when
		 ActiveMeasuresMemberInfo( gender != null , ageAtMeasurementEndDate >= 18 )
		 ProcedureEvent( endDate >= months6BeforeMeasurementEndDate , endDate <= measurementEndDate , elements contains 6204 )
	then
		ActiveMeasure mam = activeMeasureBuilder.newActiveMeasure(25); insert(mam)
end


rule "DENOM_EXCL_ACO_16_PREGNANCY_DIAG"
	dialect "mvel"
	when
		 $am : ActiveMeasure( measureId == 25 )
		 ActiveMeasuresMemberInfo( gender == Gender.FEMALE , ageAtMeasurementEndDate >= 18 )
		 DiagnosticEvent( endDate >= months12BeforeMeasurementEndDate , endDate <= measurementEndDate , elements contains 8019 )
	then
		$am.setExcludedFromDenominator(true)
end


rule "DENOM_EXCL_ACO_16_QM_NOT_ELIGIBLE_FOR_BMI_OR_FOLLOWUP_PLAN_PROC"
	dialect "mvel"
	when
		 $am : ActiveMeasure( measureId == 25 )
		 ProcedureEvent( endDate >= months12BeforeMeasurementEndDate , endDate <= measurementEndDate , elements contains 8558 )
	then
		$am.setExcludedFromDenominator(true)
end


rule "DENOM_EXCL_ACO_16_PDD_QM_QA_PREGNANCY"
	dialect "mvel"
	when
		 $am : ActiveMeasure( measureId == 25 )
		 ActiveMeasuresMemberInfo( gender == Gender.FEMALE )
		 PatientDerivedEvent( endDate >= months6BeforeMeasurementEndDate , endDate <= measurementEndDate , elements contains 7963 )
	then
		$am.setExcludedFromDenominator(true)
end


rule "DENOM_EXCL_ACO_16_BMI_SCREEN_NOT_DONE_CPT2_PROC"
	dialect "mvel"
	when
		 $am : ActiveMeasure( measureId == 25 )
		 ProcedureEvent( endDate >= months6BeforeMeasurementEndDate , endDate <= measurementEndDate , elements contains 7800 )
	then
		$am.setExcludedFromDenominator(true)
end


rule "NUM_ACO_16_QM_BMI_PAST_6_MONTHS_PROC"
	dialect "mvel"
	when
		$am : ActiveMeasure( measureId == 25 )
		ProcedureEvent( endDate >= months6BeforeMeasurementEndDate , endDate <= measurementEndDate , elements contains 8312 )
	then
		$am.setInNumerator( true );
end


rule "NUM_ACO_16_LOINC_PAST_6_MONTHS_LAB"
	dialect "mvel"
	when
		$am : ActiveMeasure( measureId == 25 )
		ActiveMeasuresMemberInfo( gender != null , ageAtMeasurementEndDate >= 18  && <= 64 )
		LabResultEvent( endDate >= months6BeforeMeasurementEndDate , endDate <= measurementEndDate , elements contains 6205 , resultValue >= 18  && <= 25 )
	then
		$am.setInNumerator( true );
end


rule "NUM_ACO_16_LOINC_MU_BMI_MGT_PAST_6_MONTHS_LAB_PROC"
	dialect "mvel"
	when
		$am : ActiveMeasure( measureId == 25 )
		ActiveMeasuresMemberInfo( gender != null , ageAtMeasurementEndDate >= 18  && <= 64 )
		LabResultEvent( endDate >= months6BeforeMeasurementEndDate , endDate <= measurementEndDate , elements contains 6205 , resultValue > 25  || < 18.5 )
		ProcedureEvent( endDate >= months6BeforeMeasurementEndDate , endDate <= measurementEndDate , elements contains 6206 )
	then
		$am.setInNumerator( true );
end


rule "NUM_ACO_16_MU_BMI_AND_BMI_INTERVENTION_RX_PAST_6_MONTHS_DIAG_DRUG"
	dialect "mvel"
	when
		$am : ActiveMeasure( measureId == 25 )
		ActiveMeasuresMemberInfo( gender != null , ageAtMeasurementEndDate >= 18 )
		DiagnosticEvent( endDate >= months6BeforeMeasurementEndDate , endDate <= measurementEndDate , elements contains 7668 )
		DrugEvent( endDate >= months6BeforeMeasurementEndDate , endDate <= measurementEndDate , elements contains 8816 )
	then
		$am.setInNumerator( true );
end


rule "NUM_ACO_16_LOINC_PAST_6_MONTHS_LAB_65_YEARS_OLDER"
	dialect "mvel"
	when
		$am : ActiveMeasure( measureId == 25 )
		ActiveMeasuresMemberInfo( gender != null , ageAtMeasurementEndDate >= 65 )
		LabResultEvent( endDate >= months6BeforeMeasurementEndDate , endDate <= measurementEndDate , elements contains 6205 , resultValue >= 23  && <= 30.1 )
	then
		$am.setInNumerator( true );
end


rule "NUM_ACO_16_MU_BMI_COUNSELING_PAST_6_MONTHS_DIAG_DIAG_65_YEARS_OLDER"
	dialect "mvel"
	when
		$am : ActiveMeasure( measureId == 25 )
		ActiveMeasuresMemberInfo( gender != null , ageAtMeasurementEndDate >= 65 )
		DiagnosticEvent( endDate >= months6BeforeMeasurementEndDate , endDate <= measurementEndDate , elements contains 7668 )
		DiagnosticEvent( endDate >= months6BeforeMeasurementEndDate , endDate <= measurementEndDate , elements contains 5289 )
	then
		$am.setInNumerator( true );
end


rule "NUM_ACO_16_QM_BMI_MU_BMI_MGT_PAST_6_MONTHS_DIAG_PROC"
	dialect "mvel"
	when
		$am : ActiveMeasure( measureId == 25 )
		ActiveMeasuresMemberInfo( gender != null , ageAtMeasurementEndDate >= 18 , ageAtMeasurementEndDate <= 64 )
		DiagnosticEvent( endDate >= months6BeforeMeasurementEndDate , endDate <= measurementEndDate , elements contains 8620 )
		ProcedureEvent( endDate >= months6BeforeMeasurementEndDate , endDate <= measurementEndDate , elements contains 6206 )
	then
		$am.setInNumerator( true );
end




