package net.ahm.activemeasure.qualitymeasures.year2015.aetnameasures.Aetna_Breast_Cancer_Screening_2015

import net.ahm.careengine.domain.member.ActiveMeasuresMemberInfo
import net.ahm.careengine.domain.measures.active.ActiveMeasureRuleContext
import net.ahm.careengine.domain.measures.active.ActiveMeasure
import net.ahm.careengine.domain.event.lab.LabEvent
import net.ahm.careengine.domain.event.proc.ProcedureEvent
import net.ahm.careengine.domain.event.diag.DiagnosticEvent
import net.ahm.careengine.domain.measures.active.impl.MemberActiveMeasure
import net.ahm.careengine.domain.event.drug.DrugEvent
import net.ahm.careengine.util.GlobalFunctions
import net.ahm.careengine.service.activemeasure.ActiveMeasureCommandOutputIF
import java.util.Collection
import java.util.Date
import net.ahm.careengine.domain.event.pdd.PatientDerivedEvent
import net.ahm.careengine.domain.feedback.Feedback
import net.ahm.careengine.util.OverlappedEvents
import net.ahm.careengine.domain.event.claim.ClaimHeader
import net.ahm.careengine.domain.event.clinical.HieEncounter
import net.ahm.careengine.event.adt.model.DischargeDispositionStatus
import net.ahm.careengine.domain.event.Event
import net.ahm.careengine.bom.clinical.HieMood
import net.ahm.careengine.bom.clinical.HieSource
import net.ahm.careengine.util.GlobalFunctions
import net.ahm.careengine.domain.event.proc.ProcedureEvent
import net.ahm.careengine.ruleengine.DateTimeUnit
import net.ahm.careengine.domain.measures.active.ActiveMeasureClassifierBuilder
import net.ahm.careengine.domain.event.adt.BaseAdmissionDischardTransferEvent
import net.ahm.careengine.domain.member.MemberInfo
import net.ahm.careengine.domain.classifier.Classifier
import net.ahm.careengine.domain.temporal.ContiguousDays
import net.ahm.careengine.domain.member.GenderSelection
import net.ahm.careengine.ruleengine.DroolEditor
import net.ahm.careengine.domain.feedback.Feedback.FeedbackReferenceType
import net.ahm.careengine.util.Month
import net.ahm.careengine.util.CEDateUtil

global java.util.Date measurementEndDate
global net.ahm.careengine.domain.measures.active.ActiveMeasureBuilder activeMeasureBuilder
global java.util.Date months12BeforeMeasurementEndDate
global java.util.Date years10BeforeMeasurementEndDate
global java.util.Date years5BeforeMeasurementEndDate
global java.util.Date months24BeforeMeasurementEndDate
global java.util.Date months3BeforeMeasurementEndDate
global java.util.Date months1BeforeMeasurementEndDate
global net.ahm.careengine.domain.measures.active.ActiveMeasureClassifierBuilder classifierBuilder















rule "DENOM_EXCL_HEDIS_BILATERAL_MASTECTOMY"
	dialect "mvel"
	when
		$am : ActiveMeasure( measureId == 61 )
		ProcedureEvent( elements contains 6112 , endDate <= measurementEndDate )
	then
		$am.setExcludedFromDenominator( true );
end


rule "DENOM_EXCL_HEDIS_UNI_MASTECTOMY_RT_AND_LT"
	dialect "mvel"
	when
		$am : ActiveMeasure( measureId == 61 )
		ProcedureEvent( elements contains 8444 , endDate <= measurementEndDate )
		ProcedureEvent( elements contains 8443 , endDate <= measurementEndDate )
	then
		$am.setExcludedFromDenominator( true );
end


rule "DENOM_EXCL_PDD_QM_QA_MASTECTOMY"
	dialect "mvel"
	when
		$am : ActiveMeasure( measureId == 61 )
		PatientDerivedEvent( elements contains 8412 , endDate <= measurementEndDate )
	then
		$am.setExcludedFromDenominator( true );
end


rule "DENOM_EXCL_TWO_HEDIS_UNILATERAL_MASTECTOMY"
	dialect "mvel"
	when
		 $am : ActiveMeasure( measureId == 61 )
		 $procedures : java.util.Collection( ) from collect ( ProcedureEvent( elements contains 6113 , endDate <= measurementEndDate )) 
		java.util.Collection(size >=  2) from collect (Event() from(GlobalFunctions.removeTooCloseEvents($procedures, 14, DateTimeUnit.DAY)))
	then
		 $am.setExcludedFromDenominator( true );
end


rule "NUM_HEDIS_MAMMOGRAM_CPT"
	dialect "mvel"
	when
		$am : ActiveMeasure( measureId == 61 )
		Classifier( id == 43 )
	then
		$am.setInNumerator( true );
end


rule "NUM_INELIGIBILITY_1DAY_MULTIPLE_GAP_YR_BEFORE_MEASUREMENT_YR"
	dialect "mvel"
	when
		 $am : ActiveMeasure( measureId == 61 )
		 not (Classifier( id == 43 )) 
		$yrBeforeMeasurementYear : java.util.Date() from GlobalFunctions.startDayOfRangeEndingOn(measurementEndDate, 12, DateTimeUnit.MONTH)
		MemberInfo ( $initialGapDays2 : enrolmentGapDays ); java.util.Collection( size >=  2 ) from collect ( ContiguousDays( durationInDays >=  1) from GlobalFunctions.filterWholeDays( $initialGapDays2, GlobalFunctions.startDayOfRangeEndingOn( $yrBeforeMeasurementYear, 1, DateTimeUnit.YEAR ) , $yrBeforeMeasurementYear ) )
	then
		 $am.setEligible( false );
end


rule "NUM_INELIGIBILITY_1DAY_GAP_OCT_1_TO_DEC_31_TWO_YRS_PRIOR"
	dialect "mvel"
	when
		 $am : ActiveMeasure( measureId == 61 )
		 not (Classifier( id == 43 )) 
		$startDate : java.util.Date() from GlobalFunctions.startDayOfRangeEndingOn(measurementEndDate, 27, DateTimeUnit.MONTH)
		$endDate : java.util.Date() from GlobalFunctions.getEarlierDate(measurementEndDate, 2, DateTimeUnit.YEAR)
		MemberInfo ( $initialGapDays2 : enrolmentGapDays ); java.util.Collection( size >=  1 ) from collect ( ContiguousDays( durationInDays >=  1) from GlobalFunctions.filterWholeDays( $initialGapDays2, $startDate, $endDate ) )
	then
		 $am.setEligible( false );
end




rule "NUM_INELIGIBILITY_46_DAY_GAP_YR_BEFORE_MEASUREMENT_YR"
	dialect "mvel"
	when
		 $am : ActiveMeasure( measureId == 61 )
		 not (Classifier( id == 43 )) 
		$yrBeforeMeasurementYear : java.util.Date() from GlobalFunctions.startDayOfRangeEndingOn(measurementEndDate, 12, DateTimeUnit.MONTH)
		MemberInfo ( $initialGapDays2 : enrolmentGapDays ); java.util.Collection( size >=  1 ) from collect ( ContiguousDays( durationInDays >=  46) from GlobalFunctions.filterWholeDays( $initialGapDays2, GlobalFunctions.startDayOfRangeEndingOn( $yrBeforeMeasurementYear, 12, DateTimeUnit.MONTH ) , $yrBeforeMeasurementYear ) )
	then
		 $am.setEligible( false );
end


rule "AM61_DENOM_BREAST_CANCER"
	dialect "mvel"
	when
		$dobMax : java.util.Date() from GlobalFunctions.startDayOfRangeEndingOn(measurementEndDate, 627, DateTimeUnit.MONTH)
		 ActiveMeasuresMemberInfo( gender == Gender.FEMALE , birthDate <= ( $dobMax ) , ageAtMeasurementEndDate <= 74 )
	then
		ActiveMeasure mam = activeMeasureBuilder.newActiveMeasure(61); insert(mam)
end


