package net.ahm.activemeasure.qualitymeasures.year2017.HEDIS.AM198_HEDIS_Childhood_Immunization_Status_DTap_2017

import net.ahm.careengine.domain.measures.active.ActiveMeasure
import net.ahm.careengine.domain.member.ActiveMeasuresMemberInfo
import net.ahm.careengine.domain.measures.active.ActiveMeasureRuleContext
import net.ahm.careengine.domain.event.lab.LabEvent
import net.ahm.careengine.domain.event.lab.LabResultEvent
import net.ahm.careengine.domain.event.proc.ProcedureEvent
import net.ahm.careengine.domain.event.diag.DiagnosticEvent
import net.ahm.careengine.domain.measures.active.impl.MemberActiveMeasure
import net.ahm.careengine.domain.event.drug.DrugEvent
import net.ahm.careengine.util.GlobalFunctions
import net.ahm.careengine.service.activemeasure.ActiveMeasureCommandOutputIF
import java.util.Collection
import java.util.Date
import net.ahm.careengine.domain.feedback.Feedback
import net.ahm.careengine.domain.measures.active.ActiveMeasureBuilder
import net.ahm.careengine.domain.event.claim.ClaimHeader
import net.ahm.careengine.domain.event.clinical.HieEncounter
import net.ahm.careengine.event.adt.model.DischargeDispositionStatus
import net.ahm.careengine.domain.event.pdd.PatientDerivedEvent
import net.ahm.careengine.ruleengine.DroolEditor
import net.ahm.careengine.domain.event.Event
import net.ahm.careengine.ruleengine.DateTimeUnit
import net.ahm.careengine.util.OverlappedEvents
import net.ahm.careengine.domain.classifier.Classifier
import net.ahm.careengine.domain.classifier.ClassifierBuilder
import net.ahm.careengine.domain.measures.active.ActiveMeasureBuilder
import net.ahm.careengine.domain.measures.active.ActiveMeasureClassifierBuilder

global java.util.Date measurementEndDate
global net.ahm.careengine.domain.measures.active.ActiveMeasureClassifierBuilder classifierBuilder
global net.ahm.careengine.domain.measures.active.ActiveMeasureBuilder activeMeasureBuilder
global java.util.Date months12BeforeMeasurementEndDate
global java.util.Date months6BeforeMeasurementEndDate
global java.util.Date months24BeforeMeasurementEndDate
global java.util.Date months27BeforeMeasurementEndDate
global java.util.Date years10BeforeMeasurementEndDate
global java.util.Date years5BeforeMeasurementEndDate


















rule "AM198_DENOM"
	dialect "mvel"
	when
		 ActiveMeasuresMemberInfo( ageAtMeasurementEndDate >= 2  && < 3 , $Dob : birthDate != null , gender != null )
		$year2AfterDob : java.util.Date() from GlobalFunctions.getLaterDate($Dob, 2, DateTimeUnit.YEAR)
	then
		ActiveMeasure mam = activeMeasureBuilder.newActiveMeasureWithAlternateStartAndEndDate(198 , $year2AfterDob , $Dob); insert(mam)
end


rule "AM198_DENOM_EXCL_DX_6082"
	dialect "mvel"
	when
		$am : ActiveMeasure( measureId == 198 )
		DiagnosticEvent( elements contains 6082 , startDate <= measurementEndDate )
	then
		$am.setExcludedFromDenominator( true );
end


rule "AM198_DENOM_EXCL_DX_6086_WITH_6085"
	dialect "mvel"
	when
		$am : ActiveMeasure( measureId == 198 )
		DiagnosticEvent( elements contains 6086 , startDate <= measurementEndDate , $dxDates : contiguousDays != null )
		DiagnosticEvent( elements contains 6085 , contiguousDays != null , eval( contiguousDays.intersectsButNotAdjacent($dxDates) ), startDate <= measurementEndDate )
	then
		$am.setExcludedFromDenominator( true );
end


rule "AM198_NUM_4_PROC_6088"
	dialect "mvel"
	when
		$am : ActiveMeasure(measureId == 198)
		 ActiveMeasuresMemberInfo( $dob : birthDate != null )
		$day42AfterBirth : java.util.Date() from GlobalFunctions.getLaterDate($dob, 42, DateTimeUnit.DAY)
		 collections : java.util.Collection( size >= 4 ) from collect ( ProcedureEvent( elements contains 6088 , startDate >= ( $day42AfterBirth ) , startDate <= ( $am.getAlternateStartDate() )  && <= ( measurementEndDate ) )) 
		java.util.Collection(size >=  4) from collect (Event() from(GlobalFunctions.removeTooCloseEvents(collections, 1, DateTimeUnit.DAY)))
	then
		$am.setInNumerator(true)
end


rule "AM198_NUM_4_RX_9443"
	dialect "mvel"
	when
		$am : ActiveMeasure(measureId == 198)
		 ActiveMeasuresMemberInfo( $dob : birthDate != null )
		$day42AfterBirth : java.util.Date() from GlobalFunctions.getLaterDate($dob, 42, DateTimeUnit.DAY)
		 collections : java.util.Collection( size >= 4 ) from collect ( DrugEvent( elements contains 9443 , startDate >= ( $day42AfterBirth ) , startDate <= ( $am.getAlternateStartDate() )  && <= measurementEndDate )) 
		java.util.Collection(size >=  4) from collect (Event() from(GlobalFunctions.removeTooCloseEvents(collections, 1, DateTimeUnit.DAY)))
	then
		$am.setInNumerator(true)
end


