package net.ahm.activemeasure.qualitymeasures.year2016.ACO.AM144_ACO_19_Colorectal_Cancer_Screening_2016

import net.ahm.careengine.domain.member.ActiveMeasuresMemberInfo
import net.ahm.careengine.domain.measures.active.ActiveMeasureRuleContext
import net.ahm.careengine.domain.measures.active.ActiveMeasure
import net.ahm.careengine.domain.event.lab.LabEvent
import net.ahm.careengine.domain.event.proc.ProcedureEvent
import net.ahm.careengine.domain.event.diag.DiagnosticEvent
import net.ahm.careengine.domain.measures.active.impl.MemberActiveMeasure
import net.ahm.careengine.domain.event.drug.DrugEvent
import net.ahm.careengine.util.GlobalFunctions
import net.ahm.careengine.service.activemeasure.ActiveMeasureCommandOutputIF
import java.util.Collection
import java.util.Date
import net.ahm.careengine.domain.event.pdd.PatientDerivedEvent
import net.ahm.careengine.domain.feedback.Feedback
import net.ahm.careengine.util.OverlappedEvents
import net.ahm.careengine.domain.event.claim.ClaimHeader
import net.ahm.careengine.domain.event.clinical.HieEncounter
import net.ahm.careengine.event.adt.model.DischargeDispositionStatus
import net.ahm.careengine.domain.event.Event
import net.ahm.careengine.bom.clinical.HieMood
import net.ahm.careengine.bom.clinical.HieSource
import net.ahm.careengine.util.GlobalFunctions
import net.ahm.careengine.domain.event.proc.ProcedureEvent
import net.ahm.careengine.ruleengine.DateTimeUnit
import net.ahm.careengine.domain.measures.active.ActiveMeasureClassifierBuilder
import net.ahm.careengine.domain.event.adt.BaseAdmissionDischardTransferEvent
import net.ahm.careengine.domain.member.MemberInfo
import net.ahm.careengine.domain.classifier.Classifier
import net.ahm.careengine.domain.temporal.ContiguousDays
import net.ahm.careengine.domain.member.GenderSelection
import net.ahm.careengine.ruleengine.DroolEditor
import net.ahm.careengine.domain.feedback.Feedback.FeedbackReferenceType
import net.ahm.careengine.util.Month
import net.ahm.careengine.util.CEDateUtil

global java.util.Date measurementEndDate
global net.ahm.careengine.domain.measures.active.ActiveMeasureBuilder activeMeasureBuilder
global java.util.Date months12BeforeMeasurementEndDate
global java.util.Date years10BeforeMeasurementEndDate
global java.util.Date years5BeforeMeasurementEndDate
global java.util.Date months24BeforeMeasurementEndDate
global java.util.Date months3BeforeMeasurementEndDate
global java.util.Date months1BeforeMeasurementEndDate
global net.ahm.careengine.domain.measures.active.ActiveMeasureClassifierBuilder classifierBuilder















rule "AM144_DENOM"
	dialect "mvel"
	when
		 ActiveMeasuresMemberInfo( gender != null , ageAtMeasurementEndDate <= 75 , ageAtMeasurementEndDate >= 50 )
		 ProcedureEvent( elements contains 8684 , endDate <= measurementEndDate , endDate >= months12BeforeMeasurementEndDate )
	then
		ActiveMeasure mam = activeMeasureBuilder.newActiveMeasure(144); insert(mam)
end


rule "AM144_DENOM_EXCL"
	dialect "mvel"
	when
		$am : ActiveMeasure( measureId == 144 )
		( ProcedureEvent( elements contains 8021 , endDate <= measurementEndDate ) or DiagnosticEvent( elements contains 8022 , endDate <= measurementEndDate ) or ProcedureEvent( elements contains 7801 , endDate <= measurementEndDate , endDate >= months12BeforeMeasurementEndDate ) or ProcedureEvent( elements contains 2675 , endDate <= measurementEndDate , endDate >= months12BeforeMeasurementEndDate ) or DiagnosticEvent( elements contains 8300 , endDate <= measurementEndDate , endDate >= months12BeforeMeasurementEndDate ) )
	then
		$am.setExcludedFromDenominator( true );
end


rule "AM144_NUM"
	dialect "mvel"
	when
		$am : ActiveMeasure( measureId == 144 )
		( ProcedureEvent( elements contains 7728 , endDate <= measurementEndDate  && >= months12BeforeMeasurementEndDate ) or LabEvent( elements contains 7729 , endDate <= measurementEndDate  && >= months12BeforeMeasurementEndDate ) or DiagnosticEvent( elements contains 5952 , endDate <= measurementEndDate  && >= months12BeforeMeasurementEndDate ) or ProcedureEvent( elements contains 8014 , endDate <= measurementEndDate  && >= years5BeforeMeasurementEndDate ) or ProcedureEvent( elements contains 8538 , endDate <= measurementEndDate  && >= years10BeforeMeasurementEndDate ) or ProcedureEvent( elements contains 5004 , endDate <= measurementEndDate  && >= months12BeforeMeasurementEndDate ) )
	then
		$am.setInNumerator( true );
end




