package net.ahm.activemeasure.qualitymeasures.year2017.aetnameasures.AM253_Aetna_Diabetes_Care_HbA1c_Control_Greater_Than_9_2017

import net.ahm.careengine.domain.member.MemberInfo
import net.ahm.careengine.domain.measures.active.impl.MemberActiveMeasure
import net.ahm.careengine.domain.measures.active.ActiveMeasure
import net.ahm.careengine.domain.event.proc.ProcedureEvent
import net.ahm.careengine.domain.event.diag.DiagnosticEvent
import net.ahm.careengine.domain.member.GenderSelection
import net.ahm.careengine.service.activemeasure.ActiveMeasureCommandOutputIF
import net.ahm.careengine.domain.member.Gender
import net.ahm.careengine.ruleengine.DroolEditor
import net.ahm.careengine.domain.event.drug.DrugEvent
import net.ahm.careengine.domain.measures.active.ActiveMeasureRuleContext
import net.ahm.careengine.util.GlobalFunctions
import net.ahm.careengine.ruleengine.DateTimeUnit
import java.util.Collection
import java.util.Date
import net.ahm.careengine.domain.event.CodifiedEvent
import net.ahm.careengine.domain.event.lab.LabEvent
import net.ahm.careengine.domain.event.lab.LabResultEvent
import net.ahm.careengine.util.OverlappedEvents
import net.ahm.careengine.domain.classifier.Classifier
import net.ahm.careengine.domain.classifier.ClassifierBuilder
import net.ahm.careengine.domain.feedback.Feedback
import net.ahm.careengine.domain.event.claim.ClaimHeader
import net.ahm.careengine.domain.event.clinical.HieEncounter
import net.ahm.careengine.event.adt.model.DischargeDispositionStatus
import net.ahm.careengine.domain.member.ActiveMeasuresMemberInfo
import net.ahm.careengine.domain.event.pdd.PatientDerivedEvent
import net.ahm.careengine.domain.event.Event
import net.ahm.careengine.util.CEDateUtil
import net.ahm.careengine.domain.temporal.TemporalUtil
import net.ahm.careengine.util.Month
import net.ahm.careengine.domain.event.claim.ClaimLabResultInfo
import net.ahm.careengine.domain.event.claim.ClaimBaseInfo
import net.ahm.careengine.domain.event.claim.ClaimLabInfo
import net.ahm.careengine.domain.event.claim.ClaimDiagnosticInfo
import net.ahm.careengine.domain.event.claim.ClaimProcedureInfo
import net.ahm.careengine.domain.event.claim.ClaimDrugInfo

global java.util.Date measurementEndDate
global net.ahm.careengine.domain.measures.active.ActiveMeasureBuilder activeMeasureBuilder
global java.util.Date months12BeforeMeasurementEndDate
global java.util.Date months24BeforeMeasurementEndDate
global java.util.Date months27BeforeMeasurementEndDate
global java.util.Date years10BeforeMeasurementEndDate
global java.util.Date years5BeforeMeasurementEndDate
global java.util.Date months6BeforeMeasurementEndDate




















rule "AM253_DENOM_EXCL_LATEST_HBA1C_LOINC_LAB_LESS_THAN_2_OR_GR_THAN_18"
	dialect "mvel"
	when
		 $am : ActiveMeasure( measureId == 253 )
		 $latestEvent : CodifiedEvent( elements contains 5887 ) from accumulate ( $allEvents : CodifiedEvent( endDate <= measurementEndDate , endDate >= months12BeforeMeasurementEndDate , elements contains 5887 ),
			latestEvent($allEvents)) 
		 LabResultEvent( resultValue < 2  || > 18 ) from $latestEvent
	then
		$am.setExcludedFromDenominator(true)
end


rule "AM253_DENOM_LAB_5887"
	dialect "mvel"
	when
		 ActiveMeasuresMemberInfo( ageAtMeasurementEndDate >= 18 , ageAtMeasurementEndDate <= 75 )
		 Classifier( id in ( 27, 25, 26 ) )
		 java.util.Collection( size >= 0 ) from collect ( LabEvent( elements contains 5887 , endDate <= measurementEndDate  && >= months12BeforeMeasurementEndDate )) 
	then
		ActiveMeasure mam = activeMeasureBuilder.newActiveMeasure(253); insert(mam)
end


rule "AM253_DENOM_PROC_5886"
	dialect "mvel"
	when
		 ActiveMeasuresMemberInfo( ageAtMeasurementEndDate >= 18 , ageAtMeasurementEndDate <= 75 )
		 Classifier( id in ( 27, 25, 26 ) )
		 java.util.Collection( size >= 0 ) from collect ( ProcedureEvent( elements contains 5886 , endDate <= measurementEndDate  && >= months12BeforeMeasurementEndDate )) 
	then
		ActiveMeasure mam = activeMeasureBuilder.newActiveMeasure(253); insert(mam)
end


rule "AM253_DENOM_EXCL_ABSENCE_HEDIS_HBA1C_PROC_LAB"
	dialect "mvel"
	when
		 $am : ActiveMeasure( measureId == 253 )
		 not (ProcedureEvent( elements contains 5886 , endDate <= measurementEndDate , endDate >= months12BeforeMeasurementEndDate )) 
		 not (LabEvent( elements contains 5887 , endDate >= months12BeforeMeasurementEndDate , endDate <= measurementEndDate )) 
	then
		$am.setExcludedFromDenominator(true)
end


rule "AM253_NUM_HEDIS_HBA1C_LAB_GT_9"
	dialect "mvel"
	when
		 $am : ActiveMeasure( measureId == 253 )
		 $latestEvent : CodifiedEvent( elements contains 5887 ) from accumulate ( $allEvents : CodifiedEvent( endDate <= measurementEndDate , endDate >= months12BeforeMeasurementEndDate , elements contains 5887  || contains 5886 ),
			latestEvent($allEvents)) 
		 LabResultEvent( resultValue > 9 ) from $latestEvent
	then
		$am.setInNumerator(true)
end


rule "AM253_NUM_HEDIS_HBA1C_PROC_GT_9"
	dialect "mvel"
	when
		 $am : ActiveMeasure( measureId == 253 )
		 Classifier( id == 74 )
	then
		$am.setInNumerator(true)
end


