package net.ahm.activemeasure.qualitymeasures.year2015.HEDIS.HEDIS_Total_Annual_Monitoring_Persistent_Medications_2015

import net.ahm.careengine.domain.member.MemberInfo
import net.ahm.careengine.domain.measures.active.impl.MemberActiveMeasure
import net.ahm.careengine.domain.measures.active.ActiveMeasure
import net.ahm.careengine.domain.event.proc.ProcedureEvent
import net.ahm.careengine.domain.event.diag.DiagnosticEvent
import net.ahm.careengine.domain.member.GenderSelection
import net.ahm.careengine.service.activemeasure.ActiveMeasureCommandOutputIF
import net.ahm.careengine.domain.member.Gender
import net.ahm.careengine.ruleengine.DroolEditor
import net.ahm.careengine.domain.event.drug.DrugEvent
import net.ahm.careengine.domain.measures.active.ActiveMeasureRuleContext
import net.ahm.careengine.util.GlobalFunctions
import net.ahm.careengine.ruleengine.DateTimeUnit
import java.util.Collection
import java.util.Date
import net.ahm.careengine.domain.event.CodifiedEvent
import net.ahm.careengine.domain.event.lab.LabEvent
import net.ahm.careengine.domain.event.lab.LabResultEvent
import net.ahm.careengine.util.OverlappedEvents
import net.ahm.careengine.domain.classifier.Classifier
import net.ahm.careengine.domain.classifier.ClassifierBuilder
import net.ahm.careengine.domain.feedback.Feedback
import net.ahm.careengine.domain.event.claim.ClaimHeader
import net.ahm.careengine.domain.event.clinical.HieEncounter
import net.ahm.careengine.event.adt.model.DischargeDispositionStatus
import net.ahm.careengine.domain.member.ActiveMeasuresMemberInfo
import net.ahm.careengine.domain.event.pdd.PatientDerivedEvent
import net.ahm.careengine.domain.event.Event

global java.util.Date measurementEndDate
global net.ahm.careengine.domain.measures.active.ActiveMeasureBuilder activeMeasureBuilder
global java.util.Date months12BeforeMeasurementEndDate
global java.util.Date months24BeforeMeasurementEndDate
global java.util.Date months27BeforeMeasurementEndDate
global java.util.Date years10BeforeMeasurementEndDate
global java.util.Date years5BeforeMeasurementEndDate
global java.util.Date months6BeforeMeasurementEndDate
global java.util.Date years3BeforeMeasurementEndDate












rule "DENOM_TOTAL"
	dialect "mvel"
	when
		 ActiveMeasuresMemberInfo( ageAtMeasurementEndDate >= 18 , gender != null )
		 $containsAntiHype : java.util.Collection( ) from collect ( DrugEvent( elements contains 1899 , endDate <= measurementEndDate  && >= months12BeforeMeasurementEndDate )) 
		 $containsDigoxin : java.util.Collection( ) from collect ( DrugEvent( elements contains 365 , endDate <= measurementEndDate  && >= months12BeforeMeasurementEndDate )) 
		 $containsDiuretics : java.util.Collection( ) from collect ( DrugEvent( elements contains 5899 , endDate <= measurementEndDate  && >= months12BeforeMeasurementEndDate )) 
		net.ahm.careengine.domain.measures.active.ActiveMeasureRuleContext(); java.lang.Number(intValue >=  180) from (GlobalFunctions.getTotalDaysSupplyOfDrugs($containsAntiHype,months24BeforeMeasurementEndDate,measurementEndDate))
		net.ahm.careengine.domain.measures.active.ActiveMeasureRuleContext(); java.lang.Number(intValue >=  180) from (GlobalFunctions.getTotalDaysSupplyOfDrugs($containsDigoxin,months24BeforeMeasurementEndDate,measurementEndDate))
		net.ahm.careengine.domain.measures.active.ActiveMeasureRuleContext(); java.lang.Number(intValue >=  180) from (GlobalFunctions.getTotalDaysSupplyOfDrugs($containsDiuretics,months24BeforeMeasurementEndDate,measurementEndDate))
	then
		ActiveMeasure mam = activeMeasureBuilder.newActiveMeasure(40); insert(mam)
end


rule "NUM_TOTAL"
	dialect "mvel"
	when
		$am : ActiveMeasure( measureId == 40 )
		ProcedureEvent( elements contains 5889 , endDate <= measurementEndDate  && >= months12BeforeMeasurementEndDate )
		Classifier( id == 28 )
		Classifier( id == 29 )
		Classifier( id == 30 )
	then
		$am.setInNumerator( true );
end


rule "DENOM_EXCL_TOTAL"
	dialect "mvel"
	when
		$am : ActiveMeasure( measureId == 40 )
		ProcedureEvent( elements contains 5902 , endDate <= measurementEndDate  && >= months12BeforeMeasurementEndDate )
	then
		$am.setExcludedFromDenominator( true );
end


rule "NUM_TOTAL_LAB_PANEL"
	dialect "mvel"
	when
		$am : ActiveMeasure( measureId == 40 )
		ProcedureEvent( elements contains 5889 , endDate <= measurementEndDate , endDate >= months12BeforeMeasurementEndDate )
	then
		$am.setInNumerator( true );
end


rule "NUM_TOTAL_POTASSIUM_DIGOXIN_CREATININE"
	dialect "mvel"
	when
		$am : ActiveMeasure( measureId == 40 )
		Classifier( id == 29 )
		Classifier( id == 30 )
		Classifier( id == 28 )
	then
		$am.setInNumerator( true );
end




