package net.ahm.activemeasure.qualitymeasures.year2016.HEDIS.AM83_HEDIS_Chlamydia_Screening_AGE_21_To_24_2016

import net.ahm.careengine.domain.member.MemberInfo
import net.ahm.careengine.domain.measures.active.impl.MemberActiveMeasure
import net.ahm.careengine.domain.measures.active.ActiveMeasure
import net.ahm.careengine.domain.event.proc.ProcedureEvent
import net.ahm.careengine.domain.event.diag.DiagnosticEvent
import net.ahm.careengine.domain.member.GenderSelection
import net.ahm.careengine.service.activemeasure.ActiveMeasureCommandOutputIF
import net.ahm.careengine.domain.member.Gender
import net.ahm.careengine.ruleengine.DroolEditor
import net.ahm.careengine.domain.event.drug.DrugEvent
import net.ahm.careengine.domain.measures.active.ActiveMeasureRuleContext
import net.ahm.careengine.util.GlobalFunctions
import net.ahm.careengine.ruleengine.DateTimeUnit
import java.util.Collection
import java.util.Date
import net.ahm.careengine.domain.event.CodifiedEvent
import net.ahm.careengine.domain.event.lab.LabEvent
import net.ahm.careengine.domain.event.lab.LabResultEvent
import net.ahm.careengine.util.OverlappedEvents
import net.ahm.careengine.domain.classifier.Classifier
import net.ahm.careengine.domain.classifier.ClassifierBuilder
import net.ahm.careengine.domain.feedback.Feedback
import net.ahm.careengine.domain.event.claim.ClaimHeader
import net.ahm.careengine.domain.event.clinical.HieEncounter
import net.ahm.careengine.event.adt.model.DischargeDispositionStatus
import net.ahm.careengine.domain.member.ActiveMeasuresMemberInfo
import net.ahm.careengine.domain.event.pdd.PatientDerivedEvent
import net.ahm.careengine.domain.event.Event
import net.ahm.careengine.util.CEDateUtil
import net.ahm.careengine.domain.temporal.TemporalUtil
import net.ahm.careengine.util.Month

global java.util.Date measurementEndDate
global net.ahm.careengine.domain.measures.active.ActiveMeasureBuilder activeMeasureBuilder
global java.util.Date months12BeforeMeasurementEndDate
global java.util.Date months24BeforeMeasurementEndDate
global java.util.Date months27BeforeMeasurementEndDate
global java.util.Date years10BeforeMeasurementEndDate
global java.util.Date years5BeforeMeasurementEndDate
global java.util.Date months6BeforeMeasurementEndDate









rule "AM83_DENOM_EXCL_PDD_8456"
	dialect "mvel"
	when
		$am : ActiveMeasure( measureId == 83 )
		PatientDerivedEvent( elements contains 8456 , endDate <= measurementEndDate , endDate >= months12BeforeMeasurementEndDate )
	then
		$am.setExcludedFromDenominator( true );
end


rule "AM83_NUM_PROC_5957"
	dialect "mvel"
	when
		$am : ActiveMeasure( measureId == 83 )
		java.util.Collection( empty == false ) from collect ( ProcedureEvent( elements contains 5957 , endDate <= measurementEndDate  && >= months12BeforeMeasurementEndDate )) 
	then
		$am.setInNumerator( true );
end


rule "AM83_NUM_LAB_5956"
	dialect "mvel"
	when
		$am : ActiveMeasure( measureId == 83 )
		java.util.Collection( empty == false ) from collect ( LabEvent( elements contains 5956 , endDate <= measurementEndDate  && >= months12BeforeMeasurementEndDate )) 
	then
		$am.setInNumerator( true );
end


rule "AM83_DENOM_EXCL_PDD_8796"
	dialect "mvel"
	when
		$am : ActiveMeasure( measureId == 83 )
		PatientDerivedEvent( elements contains 8796 , endDate <= measurementEndDate , endDate >= months12BeforeMeasurementEndDate )
	then
		$am.setExcludedFromDenominator( true );
end




rule "AM83_DENOM_DX_6200"
	dialect "mvel"
	when
		 ActiveMeasuresMemberInfo( gender == Gender.FEMALE , ageAtMeasurementEndDate <= 24 , ageAtMeasurementEndDate >= 21 )
		 java.util.Collection( empty == false ) from collect ( DiagnosticEvent( elements contains 6200 , endDate >= months12BeforeMeasurementEndDate  && <= measurementEndDate )) 
	then
		ActiveMeasure mam = activeMeasureBuilder.newActiveMeasure(83); insert(mam)
end


rule "AM83_DENOM_DX5958"
	dialect "mvel"
	when
		 ActiveMeasuresMemberInfo( gender == Gender.FEMALE , ageAtMeasurementEndDate <= 24 , ageAtMeasurementEndDate >= 21 )
		 java.util.Collection( empty == false ) from collect ( DiagnosticEvent( elements contains 5958 , endDate <= measurementEndDate  && >= months12BeforeMeasurementEndDate )) 
	then
		ActiveMeasure mam = activeMeasureBuilder.newActiveMeasure(83); insert(mam)
end


rule "AM83_DENOM_DRUG5971"
	dialect "mvel"
	when
		 ActiveMeasuresMemberInfo( gender == Gender.FEMALE , ageAtMeasurementEndDate <= 24 , ageAtMeasurementEndDate >= 21 )
		 java.util.Collection( empty == false ) from collect ( DrugEvent( elements contains 5973 , endDate <= measurementEndDate  && >= months12BeforeMeasurementEndDate )) 
	then
		ActiveMeasure mam = activeMeasureBuilder.newActiveMeasure(83); insert(mam)
end


rule "AM83_DENOM_PROC_5959"
	dialect "mvel"
	when
		 ActiveMeasuresMemberInfo( gender == Gender.FEMALE , ageAtMeasurementEndDate <= 24 , ageAtMeasurementEndDate >= 21 )
		 java.util.Collection( empty == false ) from collect ( ProcedureEvent( elements contains 5959 , endDate >= months12BeforeMeasurementEndDate  && <= measurementEndDate )) 
	then
		ActiveMeasure mam = activeMeasureBuilder.newActiveMeasure(83); insert(mam)
end


rule "AM83_DENOM_EXCLUSION_LAB_5954"
	dialect "mvel"
	when
		$am : ActiveMeasure( measureId == 83 )
		java.util.Collection( empty == false ) from collect ( LabEvent( elements contains 5954 , endDate <= measurementEndDate  && >= months12BeforeMeasurementEndDate )) 
		java.util.Collection( empty == false ) from collect ( Classifier( id in ( 61, 62, 63, 64 ) )) 
	then
		$am.setExcludedFromDenominator( true );
end


rule "AM83_DENOM_EXCLUSION_PROC_5955"
	dialect "mvel"
	when
		$am : ActiveMeasure( measureId == 83 )
		java.util.Collection( empty == false ) from collect ( ProcedureEvent( elements contains 5955 , endDate <= measurementEndDate  && >= months12BeforeMeasurementEndDate )) 
		java.util.Collection( empty == false ) from collect ( Classifier( id in ( 61, 62, 63, 64 ) )) 
	then
		$am.setExcludedFromDenominator( true );
end


