package net.ahm.activemeasure.qualitymeasures.year2015.HEDIS.HEDIS_Digoxin_Annual_Monitoring_Persistent_Medications_2015

import net.ahm.careengine.domain.member.MemberInfo
import net.ahm.careengine.domain.measures.active.impl.MemberActiveMeasure
import net.ahm.careengine.domain.measures.active.ActiveMeasure
import net.ahm.careengine.domain.event.proc.ProcedureEvent
import net.ahm.careengine.domain.event.diag.DiagnosticEvent
import net.ahm.careengine.domain.member.GenderSelection
import net.ahm.careengine.service.activemeasure.ActiveMeasureCommandOutputIF
import net.ahm.careengine.domain.member.Gender
import net.ahm.careengine.ruleengine.DroolEditor
import net.ahm.careengine.domain.event.drug.DrugEvent
import net.ahm.careengine.domain.measures.active.ActiveMeasureRuleContext
import net.ahm.careengine.util.GlobalFunctions
import net.ahm.careengine.ruleengine.DateTimeUnit
import java.util.Collection
import java.util.Date
import net.ahm.careengine.domain.event.CodifiedEvent
import net.ahm.careengine.domain.event.lab.LabEvent
import net.ahm.careengine.domain.event.lab.LabResultEvent
import net.ahm.careengine.util.OverlappedEvents
import net.ahm.careengine.domain.classifier.Classifier
import net.ahm.careengine.domain.classifier.ClassifierBuilder
import net.ahm.careengine.domain.feedback.Feedback
import net.ahm.careengine.domain.event.claim.ClaimHeader
import net.ahm.careengine.domain.event.clinical.HieEncounter
import net.ahm.careengine.event.adt.model.DischargeDispositionStatus
import net.ahm.careengine.domain.member.ActiveMeasuresMemberInfo
import net.ahm.careengine.domain.event.pdd.PatientDerivedEvent
import net.ahm.careengine.domain.event.Event

global java.util.Date measurementEndDate
global net.ahm.careengine.domain.measures.active.ActiveMeasureBuilder activeMeasureBuilder
global java.util.Date months12BeforeMeasurementEndDate
global java.util.Date months24BeforeMeasurementEndDate
global java.util.Date months27BeforeMeasurementEndDate
global java.util.Date years10BeforeMeasurementEndDate
global java.util.Date years5BeforeMeasurementEndDate
global java.util.Date months6BeforeMeasurementEndDate
global java.util.Date years3BeforeMeasurementEndDate










rule "DENOM_ANNUAL_MONITORING_PERSISTENT_MEDICATION_DIGOXIN"
	dialect "mvel"
	when
		 ActiveMeasuresMemberInfo( ageAtMeasurementEndDate >= 18 )
		 $drugCollect : java.util.Collection( empty == false ) from collect ( DrugEvent( elements contains 365 , endDate <= measurementEndDate  && >= months12BeforeMeasurementEndDate )) 
		 $drugCollectionPriorYear : java.util.Collection( ) from collect ( DrugEvent( elements contains 365 , endDate <= measurementEndDate , endDate >= months24BeforeMeasurementEndDate )) 
		net.ahm.careengine.domain.measures.active.ActiveMeasureRuleContext(); java.lang.Number(intValue >=  180) from (GlobalFunctions.getTotalDaysSupplyOfDrugs($drugCollectionPriorYear,months24BeforeMeasurementEndDate,measurementEndDate))
	then
		ActiveMeasure mam = activeMeasureBuilder.newActiveMeasure(38); insert(mam)
end


rule "NUM_PDD_SERUM_TEST"
	dialect "mvel"
	when
		$am : ActiveMeasure( measureId == 38 )
		PatientDerivedEvent( elements contains 8865 , endDate <= measurementEndDate  && >= months12BeforeMeasurementEndDate )
	then
		$am.setInNumerator( true );
end




rule "NUM_LAB_PANEL_AND_DIGOXIN_SERUM_SET"
	dialect "mvel"
	when
		 $am : ActiveMeasure( measureId == 38 )
		 $primaryCollection : java.util.Collection( ) from collect ( ProcedureEvent( elements contains 5889 , endDate <= measurementEndDate , endDate >= months12BeforeMeasurementEndDate )) 
		 $secFirstCollectionProc : java.util.Collection( ) from collect ( ProcedureEvent( elements contains 8875 , endDate <= measurementEndDate , endDate >= months12BeforeMeasurementEndDate )) 
		 $secSecondCollectionLab : java.util.Collection( ) from collect ( LabEvent( elements contains 8874 , endDate <= measurementEndDate , endDate >= months12BeforeMeasurementEndDate )) 
net.ahm.careengine.domain.measures.active.ActiveMeasureRuleContext(); 		overlapAnytimeInPastName : java.util.Collection(size >=  1) from collect (OverlappedEvents() from(GlobalFunctions.getOverlappedEventsAnytimeInPast($primaryCollection, 365, DateTimeUnit.DAY, true, 1,DateTimeUnit.DAY, measurementEndDate, $secFirstCollectionProc,$secSecondCollectionLab)))
	then
		$am.setInNumerator(true)
end


rule "NUM_POTASSIUM_AND_CREATININE_SET_DIGOXIN_PROC"
	dialect "mvel"
	when
		 $am : ActiveMeasure( measureId == 38 )
		 $primaryCollectionProc : java.util.Collection( ) from collect ( ProcedureEvent( elements contains 5890 , endDate <= measurementEndDate , endDate >= months12BeforeMeasurementEndDate )) 
		 $primaryCollectionLab : java.util.Collection( ) from collect ( LabEvent( elements contains 5894 , endDate <= measurementEndDate , endDate >= months12BeforeMeasurementEndDate )) 
		$primaryCollection:java.util.Collection() from collect (java.lang.Object() from (GlobalFunctions.collectAll($primaryCollectionProc, $primaryCollectionLab)))
		 $secFirstCollectionProc : java.util.Collection( ) from collect ( ProcedureEvent( elements contains 5895 , endDate <= measurementEndDate , endDate >= months12BeforeMeasurementEndDate )) 
		 $secSecondCollectionLab : java.util.Collection( ) from collect ( LabEvent( elements contains 5896 , endDate <= measurementEndDate , endDate >= months12BeforeMeasurementEndDate )) 
net.ahm.careengine.domain.measures.active.ActiveMeasureRuleContext(); 		overlapAnytimeInPastName : java.util.Collection(size >=  1) from collect (OverlappedEvents() from(GlobalFunctions.getOverlappedEventsAnytimeInPast($primaryCollection, 365, DateTimeUnit.DAY, true, 1,DateTimeUnit.DAY, measurementEndDate, $secFirstCollectionProc,$secSecondCollectionLab)))
		 ProcedureEvent( elements contains 8875 , endDate <= measurementEndDate , endDate >= months12BeforeMeasurementEndDate )
	then
		$am.setInNumerator(true)
end


rule "NUM_POTASSIUM_AND_CREATININE_SET_DIGOXIN_LAB"
	dialect "mvel"
	when
		 $am : ActiveMeasure( measureId == 38 )
		 $primaryCollectionProc : java.util.Collection( ) from collect ( ProcedureEvent( elements contains 5890 , endDate <= measurementEndDate , endDate >= months12BeforeMeasurementEndDate )) 
		 $primaryCollectionLab : java.util.Collection( ) from collect ( LabEvent( elements contains 5894 , endDate <= measurementEndDate , endDate >= months12BeforeMeasurementEndDate )) 
		$primaryCollection:java.util.Collection() from collect (java.lang.Object() from (GlobalFunctions.collectAll($primaryCollectionProc, $primaryCollectionLab)))
		 $secFirstCollectionProc : java.util.Collection( ) from collect ( ProcedureEvent( elements contains 5895 , endDate <= measurementEndDate , endDate >= months12BeforeMeasurementEndDate )) 
		 $secSecondCollectionLab : java.util.Collection( ) from collect ( LabEvent( elements contains 5896 , endDate <= measurementEndDate , endDate >= months12BeforeMeasurementEndDate )) 
net.ahm.careengine.domain.measures.active.ActiveMeasureRuleContext(); 		overlapAnytimeInPastName : java.util.Collection(size >=  1) from collect (OverlappedEvents() from(GlobalFunctions.getOverlappedEventsAnytimeInPast($primaryCollection, 365, DateTimeUnit.DAY, true, 1,DateTimeUnit.DAY, measurementEndDate, $secFirstCollectionProc,$secSecondCollectionLab)))
		 LabEvent( elements contains 8874 , endDate <= measurementEndDate , endDate >= months12BeforeMeasurementEndDate )
	then
		$am.setInNumerator(true)
end


