package net.ahm.activemeasure.qualitymeasures.year2017.HEDIS.AM227_HEDIS_Nephropathy_Monitoring_2017

import net.ahm.careengine.domain.member.MemberInfo
import net.ahm.careengine.domain.event.claim.ClaimHeader
import net.ahm.careengine.domain.measures.active.ActiveMeasure
import net.ahm.careengine.domain.member.ActiveMeasuresMemberInfo
import net.ahm.careengine.util.GlobalFunctions
import net.ahm.careengine.service.activemeasure.ActiveMeasureCommandOutputIF
import net.ahm.careengine.domain.member.Gender
import net.ahm.careengine.domain.measures.active.ActiveMeasure
import net.ahm.careengine.domain.member.ActiveMeasuresMemberInfo
import net.ahm.careengine.domain.measures.active.ActiveMeasureRuleContext
import net.ahm.careengine.domain.measures.active.ActiveMeasure
import net.ahm.careengine.domain.event.lab.LabEvent
import net.ahm.careengine.domain.event.proc.ProcedureEvent
import net.ahm.careengine.domain.event.diag.DiagnosticEvent
import net.ahm.careengine.domain.measures.active.impl.MemberActiveMeasure
import net.ahm.careengine.domain.event.drug.DrugEvent
import net.ahm.careengine.util.OverlappedEvents
import net.ahm.careengine.util.GlobalFunctions
import net.ahm.careengine.service.activemeasure.ActiveMeasureCommandOutputIF
import java.util.Collection
import java.util.Date
import net.ahm.careengine.domain.feedback.Feedback
import net.ahm.careengine.domain.measures.active.ActiveMeasureBuilder
import net.ahm.careengine.domain.event.claim.ClaimHeader
import net.ahm.careengine.domain.event.clinical.HieEncounter
import net.ahm.careengine.event.adt.model.DischargeDispositionStatus
import net.ahm.careengine.domain.event.pdd.PatientDerivedEvent
import net.ahm.careengine.domain.event.lab.LabResultEvent
import net.ahm.careengine.bom.clinical.HieMood
import net.ahm.careengine.ruleengine.DroolEditor
import net.ahm.careengine.ruleengine.DateTimeUnit
import net.ahm.careengine.domain.event.Event
import net.ahm.careengine.domain.event.adt.BaseAdmissionDischardTransferEvent
import org.joda.time.LocalDate
import net.ahm.careengine.domain.temporal.ContiguousDays
import net.ahm.careengine.domain.measures.active.FactLevelMeasureNumerator
import net.ahm.careengine.domain.measures.active.FactLevelMeasureDenominator
import net.ahm.careengine.domain.measures.active.FactLevelMeasureBuilder
import net.ahm.careengine.domain.event.claim.ClaimLabResultInfo
import net.ahm.careengine.domain.event.claim.ClaimBaseInfo
import net.ahm.careengine.domain.event.claim.ClaimLabInfo
import net.ahm.careengine.domain.event.claim.ClaimDiagnosticInfo
import net.ahm.careengine.domain.event.claim.ClaimProcedureInfo
import net.ahm.careengine.domain.event.claim.ClaimDrugInfo
import net.ahm.careengine.domain.classifier.Classifier
import net.ahm.careengine.domain.classifier.ClassifierBuilder
import net.ahm.careengine.domain.fact.ClassifiedFact

global java.util.Date measurementEndDate
global net.ahm.careengine.domain.measures.active.ActiveMeasureBuilder activeMeasureBuilder
global java.util.Date months12BeforeMeasurementEndDate
global java.util.Date years10BeforeMeasurementEndDate
global java.util.Date years5BeforeMeasurementEndDate
global java.util.Date months24BeforeMeasurementEndDate
global java.util.Date months3BeforeMeasurementEndDate
global java.util.Date months1BeforeMeasurementEndDate
global java.util.Date measurementStartDate
global net.ahm.careengine.domain.measures.active.FactLevelMeasureBuilder factLevelMeasureBuilder
global net.ahm.careengine.domain.measures.active.ActiveMeasureClassifierBuilder classifierBuilder











rule "DENOM_DIABETES_NEPHROPATHY_MONITORING"
	dialect "mvel"
	when
		 ActiveMeasuresMemberInfo( ageAtMeasurementEndDate >= 18  && <= 75 )
		 Classifier( id in ( 27, 25, 26 ) )
	then
		ActiveMeasure mam = activeMeasureBuilder.newActiveMeasure(227); insert(mam)
end


rule "NUM_HEDIS_NEPHROPATHY_ANTIHYPE_OR_ARB-ACEI"
	dialect "mvel"
	when
		$am : ActiveMeasure( measureId == 227 )
		DrugEvent( elements contains 1899 , endDate <= measurementEndDate  && >= months12BeforeMeasurementEndDate )
	then
		$am.setInNumerator( true );
end


rule "NUM_HEDIS_NEPHROPATHY_SCREENING_OR_TREATMENT"
	dialect "mvel"
	when
		$am : ActiveMeasure( measureId == 227 )
		DiagnosticEvent( elements contains 5893 , endDate <= measurementEndDate  && >= months12BeforeMeasurementEndDate )
	then
		$am.setInNumerator( true );
end


rule "NUM_NEPHROPATHY_SCREENING_OR_TREATMENT_PROC"
	dialect "mvel"
	when
		$am : ActiveMeasure( measureId == 227 )
		ProcedureEvent( elements contains 5891 , endDate <= measurementEndDate , endDate >= months12BeforeMeasurementEndDate )
	then
		$am.setInNumerator( true );
end


rule "NUM_INPATIENT_VISIT_NEPHROPATHY"
	dialect "mvel"
	when
		$am : ActiveMeasure( measureId == 227 )
		ProcedureEvent( elements contains 8786 , endDate <= measurementEndDate , endDate >= months12BeforeMeasurementEndDate , careProviderSpecialtyGroupCode == "SPECIALTYGRP_NEPHRO" )
	then
		$am.setInNumerator( true );
end


rule "NUM_NEPHROPATHY_SCREENING_LAB"
	dialect "mvel"
	when
		$am : ActiveMeasure( measureId == 227 )
		LabEvent( elements contains 5892 , endDate >= months12BeforeMeasurementEndDate , endDate <= measurementEndDate )
	then
		$am.setInNumerator( true );
end








