package net.ahm.activemeasure.qualitymeasures.year2015.HEDIS.HEDIS_Cervical_Cancer_Screening_2015

import net.ahm.careengine.domain.member.MemberInfo
import net.ahm.careengine.domain.measures.active.impl.MemberActiveMeasure
import net.ahm.careengine.domain.measures.active.ActiveMeasure
import net.ahm.careengine.domain.event.proc.ProcedureEvent
import net.ahm.careengine.domain.event.diag.DiagnosticEvent
import net.ahm.careengine.domain.member.GenderSelection
import net.ahm.careengine.service.activemeasure.ActiveMeasureCommandOutputIF
import net.ahm.careengine.domain.member.Gender
import net.ahm.careengine.ruleengine.DroolEditor
import net.ahm.careengine.domain.event.drug.DrugEvent
import net.ahm.careengine.domain.measures.active.ActiveMeasureRuleContext
import net.ahm.careengine.util.GlobalFunctions
import net.ahm.careengine.ruleengine.DateTimeUnit
import java.util.Collection
import java.util.Date
import net.ahm.careengine.domain.event.CodifiedEvent
import net.ahm.careengine.domain.event.lab.LabEvent
import net.ahm.careengine.domain.event.lab.LabResultEvent
import net.ahm.careengine.util.OverlappedEvents
import net.ahm.careengine.domain.classifier.Classifier
import net.ahm.careengine.domain.classifier.ClassifierBuilder
import net.ahm.careengine.domain.feedback.Feedback
import net.ahm.careengine.domain.event.claim.ClaimHeader
import net.ahm.careengine.domain.event.clinical.HieEncounter
import net.ahm.careengine.event.adt.model.DischargeDispositionStatus
import net.ahm.careengine.domain.member.ActiveMeasuresMemberInfo
import net.ahm.careengine.domain.event.pdd.PatientDerivedEvent
import net.ahm.careengine.domain.event.Event

global java.util.Date measurementEndDate
global net.ahm.careengine.domain.measures.active.ActiveMeasureBuilder activeMeasureBuilder
global java.util.Date months12BeforeMeasurementEndDate
global java.util.Date months24BeforeMeasurementEndDate
global java.util.Date months27BeforeMeasurementEndDate
global java.util.Date years10BeforeMeasurementEndDate
global java.util.Date years5BeforeMeasurementEndDate
global java.util.Date months6BeforeMeasurementEndDate
global java.util.Date years3BeforeMeasurementEndDate











rule "DENOM_CERVICAL_CANCER_SCREENING"
	dialect "mvel"
	when
		 ActiveMeasuresMemberInfo( ageAtMeasurementEndDate >= 24  && <= 64 , gender == Gender.FEMALE )
	then
		ActiveMeasure mam = activeMeasureBuilder.newActiveMeasure(30); insert(mam)
end


rule "DENOM_EXCL_CAP4P_HYSTERECTOMY_ICD9"
	dialect "mvel"
	when
		$am : ActiveMeasure( measureId == 30 )
		DiagnosticEvent( endDate <= measurementEndDate , elements contains 6022 )
	then
		$am.setExcludedFromDenominator( true );
end


rule "DENOM_EXCL_CAP4P_HYSTERECTOMY_PROC"
	dialect "mvel"
	when
		$am : ActiveMeasure( measureId == 30 )
		ProcedureEvent( elements contains 6021 , endDate <= measurementEndDate )
	then
		$am.setExcludedFromDenominator( true );
end


rule "DENOM_EXCL_PDD_QM_QA_HYSTERECTOMY"
	dialect "mvel"
	when
		$am : ActiveMeasure( measureId == 30 )
		PatientDerivedEvent( elements contains 8439 , endDate <= measurementEndDate )
	then
		$am.setExcludedFromDenominator( true );
end


rule "NUM_CAP4P_CERVICAL_CANCER_SCREENING_PROC_WI_3_YEARS"
	dialect "mvel"
	when
		$am : ActiveMeasure( measureId == 30 )
		ProcedureEvent( elements contains 6023 , endDate <= measurementEndDate  && >= years3BeforeMeasurementEndDate )
	then
		$am.setInNumerator( true );
end


rule "NUM_CAP4P_CERVICAL_CANCER_SCREENING_LAB_WI_3_YEARS"
	dialect "mvel"
	when
		$am : ActiveMeasure( measureId == 30 )
		LabEvent( elements contains 6025 , endDate <= measurementEndDate  && >= years3BeforeMeasurementEndDate )
	then
		$am.setInNumerator( true );
end


rule "NUM_CERVICAL_CANCER_SCREENING_AND_HPV_TEST_WI_5_YEARS"
	dialect "mvel"
	when
		 $am : ActiveMeasure( measureId == 30 )
		 ActiveMeasuresMemberInfo( ageAtMeasurementEndDate >= 35 )
		 $screeningLabs : java.util.Collection( ) from collect ( LabEvent( elements contains 6025 , endDate <= measurementEndDate  && >= years5BeforeMeasurementEndDate )) 
		 $screeningProcedures : java.util.Collection( ) from collect ( ProcedureEvent( elements contains 6023 , endDate <= measurementEndDate  && >= years5BeforeMeasurementEndDate )) 
		$allScreenings:java.util.Collection() from collect (java.lang.Object() from (GlobalFunctions.collectAll($screeningLabs, $screeningProcedures)))
		 $hpvTestLabs : java.util.Collection( ) from collect ( LabEvent( elements contains 8441 , endDate <= measurementEndDate  && >= years5BeforeMeasurementEndDate )) 
		 $hpvTestProcedures : java.util.Collection( ) from collect ( ProcedureEvent( elements contains 8440 , endDate <= measurementEndDate  && >= years5BeforeMeasurementEndDate )) 
net.ahm.careengine.domain.measures.active.ActiveMeasureRuleContext(); 		overlapname : java.util.Collection(size >=  1) from collect (OverlappedEvents() from(GlobalFunctions.getOverlappedEvents($allScreenings, 4, DateTimeUnit.DAY, true, 1,DateTimeUnit.DAY, GlobalFunctions.startDayOfRangeEndingOn(measurementEndDate, 5, DateTimeUnit.YEAR), measurementEndDate, $hpvTestLabs , $hpvTestProcedures)))
	then
		 $am.setInNumerator( true );
end


rule "NUM_PDD_QM_QA_CERVICAL_CA_SCREEN_W_HPV"
	dialect "mvel"
	when
		$am : ActiveMeasure( measureId == 30 )
		ActiveMeasuresMemberInfo( ageAtMeasurementEndDate >= 35 )
		PatientDerivedEvent( elements contains 8438 , endDate <= measurementEndDate  && >= years5BeforeMeasurementEndDate )
	then
		$am.setInNumerator( true );
end




