package net.ahm.activemeasure.qualitymeasures.year2016.HEDIS.AM69_HEDIS_Nephropathy_Monitoring_2016

import java.util.Collection
import java.util.Date
import net.ahm.careengine.domain.member.MemberInfo
import net.ahm.careengine.domain.measures.active.impl.MemberActiveMeasure
import net.ahm.careengine.domain.measures.active.ActiveMeasure
import net.ahm.careengine.domain.event.proc.ProcedureEvent
import net.ahm.careengine.domain.event.diag.DiagnosticEvent
import net.ahm.careengine.domain.member.GenderSelection
import net.ahm.careengine.service.activemeasure.ActiveMeasureCommandOutputIF
import net.ahm.careengine.domain.member.Gender
import net.ahm.careengine.ruleengine.DroolEditor
import net.ahm.careengine.domain.event.drug.DrugEvent
import net.ahm.careengine.domain.measures.active.ActiveMeasureRuleContext
import net.ahm.careengine.util.GlobalFunctions
import net.ahm.careengine.ruleengine.DateTimeUnit
import java.util.Collection
import java.util.Date
import net.ahm.careengine.domain.event.CodifiedEvent
import net.ahm.careengine.domain.event.lab.LabEvent
import net.ahm.careengine.domain.event.lab.LabResultEvent
import net.ahm.careengine.util.OverlappedEvents
import net.ahm.careengine.domain.classifier.Classifier
import net.ahm.careengine.domain.classifier.ClassifierBuilder
import net.ahm.careengine.domain.feedback.Feedback
import net.ahm.careengine.domain.event.claim.ClaimHeader
import net.ahm.careengine.domain.event.clinical.HieEncounter
import net.ahm.careengine.event.adt.model.DischargeDispositionStatus
import net.ahm.careengine.domain.member.ActiveMeasuresMemberInfo
import net.ahm.careengine.domain.event.pdd.PatientDerivedEvent
import net.ahm.careengine.domain.event.Event

global java.util.Date measurementEndDate
global net.ahm.careengine.domain.measures.active.ActiveMeasureBuilder activeMeasureBuilder
global java.util.Date months12BeforeMeasurementEndDate
global java.util.Date months24BeforeMeasurementEndDate
global java.util.Date months27BeforeMeasurementEndDate
global java.util.Date years10BeforeMeasurementEndDate
global java.util.Date years5BeforeMeasurementEndDate
global java.util.Date months6BeforeMeasurementEndDate
global java.util.Date years3BeforeMeasurementEndDate
global java.util.Date measurementEndDate
global net.ahm.careengine.domain.measures.active.ActiveMeasureBuilder activeMeasureBuilder
global java.util.Date months12BeforeMeasurementEndDate
global java.util.Date months24BeforeMeasurementEndDate
global java.util.Date months27BeforeMeasurementEndDate
global java.util.Date years10BeforeMeasurementEndDate
global java.util.Date years5BeforeMeasurementEndDate
global java.util.Date months6BeforeMeasurementEndDate











rule "DENOM_DIABETES_NEPHROPATHY_MONITORING"
	dialect "mvel"
	when
		 ActiveMeasuresMemberInfo( ageAtMeasurementEndDate >= 18  && <= 75 )
		 java.util.Collection( empty == false ) from collect ( Classifier( id in ( 27, 25, 26 ) )) 
	then
		ActiveMeasure mam = activeMeasureBuilder.newActiveMeasure(69); insert(mam)
end


rule "NUM_HEDIS_NEPHROPATHY_SCREENING_OR_TREATMENT"
	dialect "mvel"
	when
		$am : ActiveMeasure( measureId == 69 )
		java.util.Collection( empty == false ) from collect ( DiagnosticEvent( elements contains 5893 , endDate <= measurementEndDate  && >= months12BeforeMeasurementEndDate )) 
	then
		$am.setInNumerator( true );
end


rule "NUM_PDD_QM_QA_NEPHROPATHY"
	dialect "mvel"
	when
		$am : ActiveMeasure( measureId == 69 )
		PatientDerivedEvent( elements contains 8403  || contains 8457  || contains 8608 , endDate <= measurementEndDate  && >= months12BeforeMeasurementEndDate )
	then
		$am.setInNumerator( true );
end


rule "NUM_NEPHROPATHY_SCREENING_OR_TREATMENT_PROC"
	dialect "mvel"
	when
		$am : ActiveMeasure( measureId == 69 )
		java.util.Collection( empty == false ) from collect ( ProcedureEvent( elements contains 5891 , endDate <= measurementEndDate  && >= months12BeforeMeasurementEndDate )) 
	then
		$am.setInNumerator( true );
end


rule "NUM_INPATIENT_VISIT_NEPHROPATHY"
	dialect "mvel"
	when
		$am : ActiveMeasure( measureId == 69 )
		java.util.Collection( empty == false ) from collect ( ProcedureEvent( elements contains 8786 , endDate <= measurementEndDate  && >= months12BeforeMeasurementEndDate , careProviderSpecialtyGroupCode == "SPECIALTYGRP_NEPHRO" )) 
	then
		$am.setInNumerator( true );
end


rule "NUM_NEPHROPATHY_SCREENING_LAB"
	dialect "mvel"
	when
		$am : ActiveMeasure( measureId == 69 )
		java.util.Collection( empty == false ) from collect ( LabEvent( elements contains 5892 , endDate >= months12BeforeMeasurementEndDate  && <= measurementEndDate )) 
	then
		$am.setInNumerator( true );
end




rule "AM69_DENOM_EXCL_PDD_8370"
	dialect "mvel"
	when
		$am : ActiveMeasure( measureId == 69 )
		PatientDerivedEvent( elements contains 8370 , endDate <= measurementEndDate , endDate >= months12BeforeMeasurementEndDate )
	then
		$am.setExcludedFromDenominator( true );
end




rule "AM69_NUM_HEDIS_NEPHROPATHY_ANTIHYPE_OR_ARB"
	dialect "mvel"
	when
		 $am : ActiveMeasure( measureId == 69 )
		 java.util.Collection( empty == false ) from collect ( DrugEvent( elements contains 1899 , endDate >= months12BeforeMeasurementEndDate  && <= measurementEndDate )) 
	then
		$am.setInNumerator(true)
end




rule "AM69_NUM_INPATIENT_VISIT_NEPHROPATHY_AETNA_CUSTOM"
	dialect "mvel"
	when
		$am : ActiveMeasure( measureId == 69 )
		java.util.Collection( empty == false ) from collect ( ProcedureEvent( elements contains 8786 , endDate <= measurementEndDate  && >= months12BeforeMeasurementEndDate , customCareProviderSpecialtyGroupCode == "N" )) 
	then
		$am.setInNumerator( true );
end


