package net.ahm.activemeasure.qualitymeasures.year2015.HEDIS.HEDIS_Breast_Cancer_Screening_2015

import net.ahm.careengine.domain.member.MemberInfo
import net.ahm.careengine.domain.measures.active.impl.MemberActiveMeasure
import net.ahm.careengine.domain.measures.active.ActiveMeasure
import net.ahm.careengine.domain.event.proc.ProcedureEvent
import net.ahm.careengine.domain.event.diag.DiagnosticEvent
import net.ahm.careengine.domain.member.GenderSelection
import net.ahm.careengine.service.activemeasure.ActiveMeasureCommandOutputIF
import net.ahm.careengine.domain.member.Gender
import net.ahm.careengine.ruleengine.DroolEditor
import net.ahm.careengine.domain.event.drug.DrugEvent
import net.ahm.careengine.domain.measures.active.ActiveMeasureRuleContext
import net.ahm.careengine.util.GlobalFunctions
import net.ahm.careengine.ruleengine.DateTimeUnit
import java.util.Collection
import java.util.Date
import net.ahm.careengine.domain.event.CodifiedEvent
import net.ahm.careengine.domain.event.lab.LabEvent
import net.ahm.careengine.domain.event.lab.LabResultEvent
import net.ahm.careengine.util.OverlappedEvents
import net.ahm.careengine.domain.classifier.Classifier
import net.ahm.careengine.domain.classifier.ClassifierBuilder
import net.ahm.careengine.domain.feedback.Feedback
import net.ahm.careengine.domain.event.claim.ClaimHeader
import net.ahm.careengine.domain.event.clinical.HieEncounter
import net.ahm.careengine.event.adt.model.DischargeDispositionStatus
import net.ahm.careengine.domain.member.ActiveMeasuresMemberInfo
import net.ahm.careengine.domain.event.pdd.PatientDerivedEvent
import net.ahm.careengine.domain.event.Event
import net.ahm.careengine.util.Month
import net.ahm.careengine.util.CEDateUtil
import net.ahm.careengine.domain.member.ActiveMeasuresMemberInfo
import net.ahm.careengine.domain.measures.active.ActiveMeasureRuleContext
import net.ahm.careengine.domain.measures.active.ActiveMeasure
import net.ahm.careengine.domain.event.lab.LabEvent
import net.ahm.careengine.domain.event.proc.ProcedureEvent
import net.ahm.careengine.domain.event.diag.DiagnosticEvent
import net.ahm.careengine.domain.measures.active.impl.MemberActiveMeasure
import net.ahm.careengine.domain.event.drug.DrugEvent
import net.ahm.careengine.util.GlobalFunctions
import net.ahm.careengine.service.activemeasure.ActiveMeasureCommandOutputIF
import java.util.Collection
import java.util.Date
import net.ahm.careengine.domain.event.pdd.PatientDerivedEvent
import net.ahm.careengine.domain.feedback.Feedback
import net.ahm.careengine.util.OverlappedEvents
import net.ahm.careengine.domain.event.claim.ClaimHeader
import net.ahm.careengine.domain.event.clinical.HieEncounter
import net.ahm.careengine.event.adt.model.DischargeDispositionStatus
import net.ahm.careengine.domain.event.Event
import net.ahm.careengine.bom.clinical.HieMood
import net.ahm.careengine.bom.clinical.HieSource
import net.ahm.careengine.util.GlobalFunctions
import net.ahm.careengine.domain.event.proc.ProcedureEvent
import net.ahm.careengine.ruleengine.DateTimeUnit
import net.ahm.careengine.domain.measures.active.ActiveMeasureClassifierBuilder
import net.ahm.careengine.domain.event.adt.BaseAdmissionDischardTransferEvent
import net.ahm.careengine.domain.member.MemberInfo
import net.ahm.careengine.domain.classifier.Classifier
import net.ahm.careengine.domain.temporal.ContiguousDays
import net.ahm.careengine.domain.member.GenderSelection
import net.ahm.careengine.ruleengine.DroolEditor
import net.ahm.careengine.domain.feedback.Feedback.FeedbackReferenceType
import net.ahm.careengine.util.Month
import net.ahm.careengine.util.CEDateUtil

global java.util.Date measurementEndDate
global net.ahm.careengine.domain.measures.active.ActiveMeasureBuilder activeMeasureBuilder
global java.util.Date months12BeforeMeasurementEndDate
global java.util.Date months24BeforeMeasurementEndDate
global java.util.Date months27BeforeMeasurementEndDate
global java.util.Date years10BeforeMeasurementEndDate
global java.util.Date years5BeforeMeasurementEndDate
global java.util.Date months6BeforeMeasurementEndDate
global java.util.Date measurementEndDate
global net.ahm.careengine.domain.measures.active.ActiveMeasureBuilder activeMeasureBuilder
global java.util.Date months12BeforeMeasurementEndDate
global java.util.Date years10BeforeMeasurementEndDate
global java.util.Date years5BeforeMeasurementEndDate
global java.util.Date months24BeforeMeasurementEndDate
global java.util.Date months3BeforeMeasurementEndDate
global java.util.Date months1BeforeMeasurementEndDate
global net.ahm.careengine.domain.measures.active.ActiveMeasureClassifierBuilder classifierBuilder










rule "DENOM_EXCL_HEDIS_BILATERAL_MASTECTOMY"
	dialect "mvel"
	when
		$am : ActiveMeasure( measureId == 31 )
		ProcedureEvent( elements contains 6112 , endDate <= measurementEndDate )
	then
		$am.setExcludedFromDenominator( true );
end


rule "DENOM_EXCL_TWO_HEDIS_UNILATERAL_MASTECTOMY"
	dialect "mvel"
	when
		 $am : ActiveMeasure( measureId == 31 )
		 $procedures : java.util.Collection( ) from collect ( ProcedureEvent( elements contains 6113 , endDate <= measurementEndDate )) 
		java.util.Collection(size >=  2) from collect (Event() from(GlobalFunctions.removeTooCloseEvents($procedures, 14, DateTimeUnit.DAY)))
	then
		 $am.setExcludedFromDenominator( true );
end


rule "DENOM_EXCL_HEDIS_UNI_MASTECTOMY_RT_AND_LT"
	dialect "mvel"
	when
		$am : ActiveMeasure( measureId == 31 )
		ProcedureEvent( elements contains 8444 , endDate <= measurementEndDate )
		ProcedureEvent( elements contains 8443 , endDate <= measurementEndDate )
	then
		$am.setExcludedFromDenominator( true );
end


rule "DENOM_EXCL_PDD_QM_QA_MASTECTOMY"
	dialect "mvel"
	when
		$am : ActiveMeasure( measureId == 31 )
		PatientDerivedEvent( elements contains 8412 , endDate <= measurementEndDate )
	then
		$am.setExcludedFromDenominator( true );
end


rule "NUM_HEDIS_MAMMOGRAM_CPT"
	dialect "mvel"
	when
		 $am : ActiveMeasure( measureId == 31 )
		 ActiveMeasuresMemberInfo( $dob : birthDate != null )
		$year50AfterBirthDate : java.util.Date() from GlobalFunctions.getLaterDate($dob, 50, DateTimeUnit.YEAR)
		 ProcedureEvent( elements contains 6105 , endDate <= measurementEndDate  && >= months27BeforeMeasurementEndDate , endDate >= ( $year50AfterBirthDate ) )
	then
		 $am.setInNumerator( true );
end




rule "AM31_DENOM_BREAST_CANCER"
	dialect "mvel"
	when
		$dobMax : java.util.Date() from GlobalFunctions.startDayOfRangeEndingOn(measurementEndDate, 627, DateTimeUnit.MONTH)
		 ActiveMeasuresMemberInfo( gender == Gender.FEMALE , birthDate <= ( $dobMax ) , ageAtMeasurementEndDate <= 74 )
	then
		ActiveMeasure mam = activeMeasureBuilder.newActiveMeasure(31); insert(mam)
end


