package net.ahm.activemeasure.qualitymeasures.year2016.HEDIS.AM115_HEDIS_Childhood_Immunization_Status_Hep_B_2016

import net.ahm.careengine.domain.measures.active.ActiveMeasure
import net.ahm.careengine.domain.member.ActiveMeasuresMemberInfo
import net.ahm.careengine.domain.measures.active.ActiveMeasureRuleContext
import net.ahm.careengine.domain.event.lab.LabEvent
import net.ahm.careengine.domain.event.lab.LabResultEvent
import net.ahm.careengine.domain.event.proc.ProcedureEvent
import net.ahm.careengine.domain.event.diag.DiagnosticEvent
import net.ahm.careengine.domain.measures.active.impl.MemberActiveMeasure
import net.ahm.careengine.domain.event.drug.DrugEvent
import net.ahm.careengine.util.GlobalFunctions
import net.ahm.careengine.service.activemeasure.ActiveMeasureCommandOutputIF
import java.util.Collection
import java.util.Date
import net.ahm.careengine.domain.feedback.Feedback
import net.ahm.careengine.domain.measures.active.ActiveMeasureBuilder
import net.ahm.careengine.domain.event.claim.ClaimHeader
import net.ahm.careengine.domain.event.clinical.HieEncounter
import net.ahm.careengine.event.adt.model.DischargeDispositionStatus
import net.ahm.careengine.domain.event.pdd.PatientDerivedEvent
import net.ahm.careengine.ruleengine.DroolEditor
import net.ahm.careengine.domain.event.Event
import net.ahm.careengine.ruleengine.DateTimeUnit
import net.ahm.careengine.util.OverlappedEvents
import net.ahm.careengine.domain.classifier.Classifier
import net.ahm.careengine.domain.classifier.ClassifierBuilder
import net.ahm.careengine.domain.measures.active.ActiveMeasureBuilder
import net.ahm.careengine.domain.measures.active.ActiveMeasureClassifierBuilder

global java.util.Date measurementEndDate
global net.ahm.careengine.domain.measures.active.ActiveMeasureClassifierBuilder classifierBuilder
global net.ahm.careengine.domain.measures.active.ActiveMeasureBuilder activeMeasureBuilder
global java.util.Date months12BeforeMeasurementEndDate
global java.util.Date months6BeforeMeasurementEndDate
global java.util.Date months24BeforeMeasurementEndDate
global java.util.Date months27BeforeMeasurementEndDate
global java.util.Date years10BeforeMeasurementEndDate
global java.util.Date years5BeforeMeasurementEndDate
















rule "AM115_DENOM"
	dialect "mvel"
	when
		 ActiveMeasuresMemberInfo( ageAtMeasurementEndDate >= 2  && < 3 , $Dob : birthDate != null , gender != null )
		$year2AfterDob : java.util.Date() from GlobalFunctions.getLaterDate($Dob, 2, DateTimeUnit.YEAR)
	then
		ActiveMeasure mam = activeMeasureBuilder.newActiveMeasureWithAlternateStartAndEndDate(115 , $year2AfterDob , $Dob); insert(mam)
end


rule "AM115_DENOM_EXCL_DX_6082"
	dialect "mvel"
	when
		$am : ActiveMeasure( measureId == 115 )
		DiagnosticEvent( elements contains 6082 , startDate <= measurementEndDate )
	then
		$am.setExcludedFromDenominator( true );
end


rule "AM115_NUM_PDD_8844"
	dialect "mvel"
	when
		 $am : ActiveMeasure( measureId == 115 )
		 PatientDerivedEvent( elements contains 8844 , endDate <= measurementEndDate , endDate >= months12BeforeMeasurementEndDate )
	then
		$am.setInNumerator(true)
end


rule "AM115_NUM_DX_2633"
	dialect "mvel"
	when
		 $am : ActiveMeasure( measureId == 115 )
		 DiagnosticEvent( elements contains 2633 , startDate <= ( $am.getAlternateStartDate() )  && <= ( measurementEndDate ) )
	then
		$am.setInNumerator(true)
end


rule "AM115_NUM_3_PROC_6099"
	dialect "mvel"
	when
		$am : ActiveMeasure(measureId == 115)
		 collections : java.util.Collection( empty == false ) from collect ( ProcedureEvent( elements contains 6099 , startDate <= ( $am.getAlternateStartDate() )  && <= measurementEndDate )) 
		java.util.Collection(size >=  3) from collect (Event() from(GlobalFunctions.removeTooCloseEvents(collections, 1, DateTimeUnit.DAY)))
	then
		$am.setInNumerator(true)
end


rule "AM115_NUM_ONE_PROC_9132_AND_TWO_PROC_6099"
	dialect "mvel"
	when
		$am : ActiveMeasure(measureId == 115)
		$7daysAfterBirth : java.util.Date() from GlobalFunctions.getLaterDate($am.getAlternateEndDate(), 7, DateTimeUnit.DAY)
		 collection1 : java.util.Collection( size >= 2 ) from collect ( ProcedureEvent( elements contains 6099 , startDate <= ( $am.getAlternateStartDate() )  && <= measurementEndDate )) 
		 collection2 : java.util.Collection( size >= 1 ) from collect ( ProcedureEvent( elements contains 9132 , startDate <= ( $7daysAfterBirth )  && <= measurementEndDate , startDate >= ( $am.getAlternateEndDate() ) )) 
		collections:java.util.Collection() from collect (java.lang.Object() from (GlobalFunctions.collectAll(collection1, collection2)))
		java.util.Collection(size >=  3) from collect (Event() from(GlobalFunctions.removeTooCloseEvents(collections, 1, DateTimeUnit.DAY)))
	then
		$am.setInNumerator(true)
end


