package net.ahm.activemeasure.qualitymeasures.year2015.aetnameasures.Aetna_Colorectal_Cancer_Screening_2015

import net.ahm.careengine.domain.member.ActiveMeasuresMemberInfo
import net.ahm.careengine.domain.measures.active.ActiveMeasureRuleContext
import net.ahm.careengine.domain.measures.active.ActiveMeasure
import net.ahm.careengine.domain.event.lab.LabEvent
import net.ahm.careengine.domain.event.proc.ProcedureEvent
import net.ahm.careengine.domain.event.diag.DiagnosticEvent
import net.ahm.careengine.domain.measures.active.impl.MemberActiveMeasure
import net.ahm.careengine.domain.event.drug.DrugEvent
import net.ahm.careengine.util.GlobalFunctions
import net.ahm.careengine.service.activemeasure.ActiveMeasureCommandOutputIF
import java.util.Collection
import java.util.Date
import net.ahm.careengine.domain.event.pdd.PatientDerivedEvent
import net.ahm.careengine.domain.feedback.Feedback
import net.ahm.careengine.util.OverlappedEvents
import net.ahm.careengine.domain.event.claim.ClaimHeader
import net.ahm.careengine.domain.event.clinical.HieEncounter
import net.ahm.careengine.event.adt.model.DischargeDispositionStatus
import net.ahm.careengine.domain.event.Event
import net.ahm.careengine.bom.clinical.HieMood
import net.ahm.careengine.bom.clinical.HieSource
import net.ahm.careengine.util.GlobalFunctions
import net.ahm.careengine.domain.event.proc.ProcedureEvent
import net.ahm.careengine.ruleengine.DateTimeUnit
import net.ahm.careengine.domain.measures.active.ActiveMeasureClassifierBuilder
import net.ahm.careengine.domain.event.adt.BaseAdmissionDischardTransferEvent
import net.ahm.careengine.domain.member.MemberInfo
import net.ahm.careengine.domain.classifier.Classifier
import net.ahm.careengine.domain.temporal.ContiguousDays
import net.ahm.careengine.domain.member.GenderSelection
import net.ahm.careengine.ruleengine.DroolEditor
import net.ahm.careengine.domain.feedback.Feedback.FeedbackReferenceType
import net.ahm.careengine.util.Month
import net.ahm.careengine.util.CEDateUtil

global java.util.Date measurementEndDate
global net.ahm.careengine.domain.measures.active.ActiveMeasureBuilder activeMeasureBuilder
global java.util.Date months12BeforeMeasurementEndDate
global java.util.Date years10BeforeMeasurementEndDate
global java.util.Date years5BeforeMeasurementEndDate
global java.util.Date months24BeforeMeasurementEndDate
global java.util.Date months3BeforeMeasurementEndDate
global java.util.Date months1BeforeMeasurementEndDate
global net.ahm.careengine.domain.measures.active.ActiveMeasureClassifierBuilder classifierBuilder















rule "DENOM_COLORECTAL_CANCER"
	dialect "mvel"
	when
		 ActiveMeasuresMemberInfo( ageAtMeasurementEndDate >= 50  && <= 75 )
	then
		ActiveMeasure mam = activeMeasureBuilder.newActiveMeasure(62); insert(mam)
end


rule "DENOM_EXCL_COLECTOMY_PROCEDURE"
	dialect "mvel"
	when
		$am : ActiveMeasure( measureId == 62 )
		ProcedureEvent( elements contains 5945 , endDate <= measurementEndDate )
	then
		$am.setExcludedFromDenominator( true );
end


rule "DENOM_EXCL_COLORECTAL_CANCER_DIAGNOSIS"
	dialect "mvel"
	when
		$am : ActiveMeasure( measureId == 62 )
		DiagnosticEvent( elements contains 5946 , endDate <= measurementEndDate )
	then
		$am.setExcludedFromDenominator( true );
end


rule "NUM_FECAL_OCCULT_BLOOD_TEST_PROC"
	dialect "mvel"
	when
		$am : ActiveMeasure( measureId == 62 )
		ProcedureEvent( elements contains 5948 , endDate <= measurementEndDate , endDate >= months12BeforeMeasurementEndDate )
	then
		$am.setInNumerator( true );
end


rule "NUM_SIGMOIDOSCOPY_PROC"
	dialect "mvel"
	when
		$am : ActiveMeasure( measureId == 62 )
		ProcedureEvent( elements contains 5950 , endDate <= measurementEndDate , endDate >= years5BeforeMeasurementEndDate )
	then
		$am.setInNumerator( true );
end


rule "NUM_COLONOSCOPY_PROC"
	dialect "mvel"
	when
		$am : ActiveMeasure( measureId == 62 )
		ProcedureEvent( elements contains 5951 , endDate <= measurementEndDate , endDate >= years10BeforeMeasurementEndDate )
	then
		$am.setInNumerator( true );
end


rule "NUM_FECAL_OCCULT_BLOOD_TEST_LAB"
	dialect "mvel"
	when
		$am : ActiveMeasure( measureId == 62 )
		LabEvent( elements contains 5949 , endDate <= measurementEndDate , endDate >= months12BeforeMeasurementEndDate )
	then
		$am.setInNumerator( true );
end


rule "NUM_ELIGIBILITY_MULTIPLE_GAPS"
	dialect "mvel"
	when
		 $am : ActiveMeasure( measureId == 62 )
		 not (ProcedureEvent( elements contains 5948 , endDate <= measurementEndDate , endDate >= months12BeforeMeasurementEndDate )) 
		 not (ProcedureEvent( elements contains 5950 , endDate >= years5BeforeMeasurementEndDate , endDate <= measurementEndDate )) 
		 not (ProcedureEvent( elements contains 5951 , endDate >= years10BeforeMeasurementEndDate , endDate <= measurementEndDate )) 
		 not (LabEvent( elements contains 5949 , endDate >= months12BeforeMeasurementEndDate , endDate <= measurementEndDate )) 
		oneYearBeforeMeasurementEndDate : java.util.Date() from GlobalFunctions.startDayOfRangeEndingOn(measurementEndDate, 12, DateTimeUnit.MONTH)
		MemberInfo ( $initialGapDays2 : enrolmentGapDays ); java.util.Collection( size >=  2 ) from collect ( ContiguousDays( durationInDays >=  1) from GlobalFunctions.filterWholeDays( $initialGapDays2, GlobalFunctions.startDayOfRangeEndingOn( oneYearBeforeMeasurementEndDate , 1, DateTimeUnit.YEAR ) , oneYearBeforeMeasurementEndDate  ) )
	then
		 $am.setEligible( false );
end




rule "NUM_ELIGIBILITY_46_DAYS_OR_MORE"
	dialect "mvel"
	when
		 $am : ActiveMeasure( measureId == 62 )
		 not (ProcedureEvent( elements contains 5948 , endDate <= measurementEndDate , endDate >= months12BeforeMeasurementEndDate )) 
		 not (ProcedureEvent( elements contains 5950 , endDate >= years5BeforeMeasurementEndDate , endDate <= measurementEndDate )) 
		 not (ProcedureEvent( elements contains 5951 , endDate >= years10BeforeMeasurementEndDate , endDate <= measurementEndDate )) 
		 not (LabEvent( elements contains 5949 , endDate >= months12BeforeMeasurementEndDate , endDate <= measurementEndDate )) 
		oneYearBeforeMeasurementEndDate : java.util.Date() from GlobalFunctions.startDayOfRangeEndingOn(measurementEndDate, 12, DateTimeUnit.MONTH)
		MemberInfo ( $initialGapDays2 : enrolmentGapDays ); java.util.Collection( size >=  1 ) from collect ( ContiguousDays( durationInDays >=  46) from GlobalFunctions.filterWholeDays( $initialGapDays2, GlobalFunctions.startDayOfRangeEndingOn( oneYearBeforeMeasurementEndDate , 1, DateTimeUnit.YEAR ) , oneYearBeforeMeasurementEndDate  ) )
	then
		 $am.setEligible( false );
end


